/**
 * ImageComposite composition registration.
 *
 * This file defines how the template appears in Remotion Studio
 * and provides the default/sample data for previewing.
 */

import { Composition } from "remotion";
import { ImageComposite } from "./ImageComposite";
import { standardMetadata } from "../../utils/composition";
import { ImageCompositeSchema } from "./schema";
import type { ImageCompositeData } from "./types";

const sampleData: ImageCompositeData = {
  episode: "EP00",
  title: "The Arsenal of Democracy",
  subtitle: "Detroit, 1943",
  // Synthetic test asset (480×270 grayscale gradient) generated by
  // scripts/generate-test-assets.mjs. The visual regression suite needs
  // this asset to render the ImageComposite catalog comp; the .jpg
  // production filename was a vendor placeholder that was never sourced.
  // Real episodes provide their own image paths via data.imagePath.
  imagePath: "assets/sample-historical.png",
  variant: "background",
  duotone: "standard",
  textPosition: "bottom-left",
  source: "National Archives",
  durationSec: 6,
  backgroundVariant: "dark",
};

export const ImageCompositeComposition = () => (
  <Composition
    id="ImageComposite"
    component={ImageComposite}
    schema={ImageCompositeSchema}
    calculateMetadata={standardMetadata<ImageCompositeData>(6)}
    defaultProps={{ data: sampleData }}
  />
);
