/**
 * FullEpisode — Assembly-manifest-driven episode composition.
 *
 * Replaces the manual SiliconTrap.tsx approach (29-clip Series) with a data-driven
 * composition that renders the COMPLETE video: narration audio, motion graphics,
 * stock footage with brand treatment, and transitions — all from one JSON file.
 *
 * Architecture:
 *   - Reads an assembly manifest (generated by tools/assembly/generate_manifest.py)
 *   - Bottom layer: background segments (FOOTAGE, IMAGE) with BrandImage treatment
 *   - Top layer: foreground segments (TEMPLATE, TRANSITION) positioned by timestamp
 *   - Audio layer: narration track via Remotion <Audio>
 *   - HOLD segments sustain the previous visual with an optional freeze
 *
 * Usage:
 *   Register as a Composition with the manifest as defaultProps or inputProps:
 *
 *   <Composition
 *     id="silicon-trap-full"
 *     component={FullEpisode}
 *     calculateMetadata={calculateFullEpisodeMetadata}
 *     defaultProps={{ manifestPath: "episodes/silicon-trap/assembly-manifest.json" }}
 *   />
 *
 * Then render:
 *   npx remotion render silicon-trap-full out/silicon-trap-full.mp4
 *
 * Render performance notes (from research):
 *   - Uses <OffthreadVideo> instead of <Video> for stock footage segments.
 *     Extracts frames off-thread, preventing cache eviction stalls that hit
 *     at 20-30% progress in long compositions with many short clips.
 *   - BackgroundSegment and ForegroundSegment are memoized to prevent
 *     SVG filter re-creation per frame (Chrome throttles overlapping video+SVG).
 *   - For Lambda: use memorySizeInMb: 3008 and concurrency: 4.
 *     18 min @ 1080p30 renders in ~2-5 min, well within the 5 GB file limit.
 */

import React, { useMemo, memo, Component, type ReactNode, type ErrorInfo } from "react";
import {
  AbsoluteFill,
  Audio,
  interpolate,
  OffthreadVideo,
  Sequence,
  staticFile,
  useCurrentFrame,
  useVideoConfig,
} from "remotion";
import { layout, palette, semantic } from "../../design/theme";
import { BrandImage } from "../../components/BrandImage";
import { SectionIndicator } from "../../components/SectionIndicator";
import {
  TransitionWrapper,
  type TransitionType,
} from "../../components/Transitions";
import { LayeredComposition } from "../../components/LayeredComposition";
import { LowerThird } from "../../components/LowerThird";
import { FilmOverlay } from "../../components/FilmOverlay";
import { AudioLayer } from "../../components/AudioLayer";
import type { SegmentTimeline } from "../../components/AudioLayer";
import { EpisodeColorEmphasisProvider } from "../../hooks/useEpisodeColorEmphasis";
import {
  type EpisodeMotif,
  EpisodeMotifProvider,
  SegmentMotifProgressProvider,
} from "../../hooks/useMotifProgress";
import {
  BACKDROP_MANIFEST,
  EditorialSurface,
  SegmentBackdrop,
  backdropMeta,
  backdropStaticFile,
} from "../../components/EditorialSurface";
import {
  resolveFilmOverlay,
  type FilmOverlayConfig,
} from "../../utils/resolveFilmOverlay";
import {
  EditorialModeProvider,
  modeFromBackdropRegister,
} from "../../design/editorialModes";

// ── Template imports ─��────────────────────────────────────────────────────────

import { TitleTransition } from "../TitleTransition/TitleTransition";
import { ChoroplethMap } from "../ChoroplethMap/ChoroplethMap";
import { ProportionalSymbolMap } from "../ProportionalSymbolMap/ProportionalSymbolMap";
import { KineticTypography } from "../KineticTypography/KineticTypography";
// TimelineComparison + DualTimeline are @deprecated — replaced by
// HorizontalTimeline. Removed from TEMPLATE_COMPONENTS dispatch May 18, 2026
// (engineering audit P0 #8) so manifest authors can't silently pick them.
// Source kept under src/templates/{TimelineComparison,DualTimeline}/ for
// historical reference + catalog showreel. Lint rule "no-deprecated-template-
// dispatch" in scripts/lint-conventions.mjs guards against re-add.
import { DataChart } from "../DataChart/DataChart";
import { FrameworkDiagram } from "../FrameworkDiagram/FrameworkDiagram";
import { RouteAnimation } from "../RouteAnimation/RouteAnimation";
import { DecisionTree } from "../DecisionTree/DecisionTree";
import { OutcomePartition } from "../OutcomePartition/OutcomePartition";
import { SplitComposition } from "../SplitComposition/SplitComposition";
import { ProbabilityGauge } from "../ProbabilityGauge/ProbabilityGauge";
import { ImageComposite } from "../ImageComposite/ImageComposite";
import { PhotoMontage } from "../PhotoMontage/PhotoMontage";
import { NetworkDiagram } from "../NetworkDiagram/NetworkDiagram";
import { TimeSeriesChart } from "../TimeSeriesChart/TimeSeriesChart";
import { SankeyFlow } from "../SankeyFlow/SankeyFlow";
import { GameBoard } from "../GameBoard/GameBoard";
import { BayesianUpdate } from "../BayesianUpdate/BayesianUpdate";
import { StatReveal } from "../StatReveal/StatReveal";
import { RadarChart } from "../RadarChart/RadarChart";
import { AnnotatedImage } from "../AnnotatedImage/AnnotatedImage";
import { EscalationLadder } from "../EscalationLadder/EscalationLadder";
// DualTimeline @deprecated — see comment above the TimelineComparison import.
import { HorizontalTimeline } from "../HorizontalTimeline/HorizontalTimeline";
import { ArcDiagram } from "../ArcDiagram/ArcDiagram";
import { Slopegraph } from "../Slopegraph/Slopegraph";
import { KPICard } from "../KPICard/KPICard";
import { BulletChart } from "../BulletChart/BulletChart";
import { StepLine } from "../StepLine/StepLine";
// BifurcationRoute template removed May 13, 2026 (phylogenetic-tree
// register didn't fit Parallax; no episodes in queue required it).
import { DuelingFrameworks } from "../DuelingFrameworks/DuelingFrameworks";
import { StrategicLandscape } from "../StrategicLandscape/StrategicLandscape";
import { PricingWaterfall } from "../PricingWaterfall/PricingWaterfall";
// TimelineMorph template deleted May 13, 2026 (its single use case
// migrated to DuelingFrameworks). Removed from FullEpisode template map.
import { AtlasPlate } from "../AtlasPlate/AtlasPlate";
import { BeeswarmChart } from "../BeeswarmChart/BeeswarmChart";
import { BumpChart } from "../BumpChart/BumpChart";
import { CalendarHeatmap } from "../CalendarHeatmap/CalendarHeatmap";
import { CartogramMap } from "../CartogramMap/CartogramMap";
import { ConnectedScatterplot } from "../ConnectedScatterplot/ConnectedScatterplot";
import { DensityMap } from "../DensityMap/DensityMap";
import { DumbbellPlot } from "../DumbbellPlot/DumbbellPlot";
import { HorizonChart } from "../HorizonChart/HorizonChart";
import { IsotypeChart } from "../IsotypeChart/IsotypeChart";
import { MarimekkoChart } from "../MarimekkoChart/MarimekkoChart";
import { PopulationPyramid } from "../PopulationPyramid/PopulationPyramid";
import { RankChangeDotPlot } from "../RankChangeDotPlot/RankChangeDotPlot";
import { RidgelinePlot } from "../RidgelinePlot/RidgelinePlot";
import { Streamgraph } from "../Streamgraph/Streamgraph";
import { TernaryPlot } from "../TernaryPlot/TernaryPlot";
import { TilegramUSMap } from "../TilegramUSMap/TilegramUSMap";
import { warnIf } from "../../utils/dataWarnings";

// ── Types ──────���─────────────────────────────��────────────────────────────────

type SegmentType = "FOOTAGE" | "IMAGE" | "TEMPLATE" | "TRANSITION" | "HOLD";
type LayerType = "background" | "foreground";
type DuotoneRamp = "standard" | "conflict" | "editorial";
type CompositeMode = "background" | "inset" | "antipode" | "raw";
// TransitionType imported from ../../components/Transitions

interface AssetInfo {
  shotListId?: string;
  searchTerms?: string[];
  source?: string;
  file?: string;
  status?: "pending" | "resolved" | "failed";
  placeholder?: "solid-color" | "last-frame";
  fallbackColor?: string;
}

interface TreatmentInfo {
  ramp?: DuotoneRamp;
  composite?: CompositeMode;
  opacity?: number;
}

export interface TemplateInfo {
  component: string;
  dataFile?: string;
  /** Atmospheric PNG under this template only (ids from BACKDROP_MANIFEST). */
  backdropId?: string | null;
  /**
   * Per-segment FilmOverlay override. Each of preset/effects/intensity is
   * INDEPENDENTLY optional — set just one to override that field; the others
   * resolve via the cascade. See src/utils/resolveFilmOverlay.ts. Ignored when
   * episode-level `manifest.filmOverlay` is absent (whole cascade is gated).
   *
   * Shape is `FilmOverlayConfig` (single TS source of truth — same interface
   * at episode level below). Data-side equivalent: `$defs/filmOverlayConfig`
   * in `data/assembly-manifest.schema.json` — keep both in sync when adding
   * fields (see resolveFilmOverlay.ts header comment).
   */
  filmOverlay?: FilmOverlayConfig;
}

interface HoldInfo {
  freeze?: boolean;
}

interface TransitionInfo {
  in?: TransitionType;
  out?: TransitionType;
  durationSec?: number;
  /**
   * Fill color for color-wash transitions. When absent, TransitionWrapper
   * defaults to palette.amber. Must be set whenever `in` or `out` is
   * "color-wash" — the M-TRANSITION-COLOR-WASH-TOKEN lint rule enforces this.
   */
  washColor?: string;
}

interface LayeredInfo {
  /** ID of the background segment this foreground composites over */
  backgroundSegmentId: string;
  /** Foreground position preset */
  position?: "full" | "lower-third" | "upper-third" | "center-inset" | "bottom-bar";
  /** Blend mode for the foreground */
  blendMode?: "normal" | "multiply" | "screen" | "overlay" | "soft-light";
  /** Foreground opacity 0-1 */
  foregroundOpacity?: number;
  /** Background dim amount 0-1 */
  backgroundDim?: number;
  /** Foreground fade-in duration in seconds */
  foregroundFadeInSec?: number;
  /** Show vignette overlay */
  vignette?: boolean;
}

export interface SoundCue {
  type:
    | "beat-transition"
    | "stat-reveal"
    | "tension-rise"
    | "tension-resolve"
    | "map-whoosh"
    | "quote-bell"
    | "section-open"
    | "end-stinger";
  offsetSec?: number;
  intensity?: "subtle" | "normal" | "dramatic";
}

export interface TextureCue {
  type:
    | "dot-click"
    | "card-settle"
    | "line-draw"
    | "region-glow"
    | "bar-grow"
    | "node-pop"
    | "page-turn";
  offsetSec: number;
  volume?: number;
  label?: string;
}

interface SyncPoint {
  word: string;
  /** Absolute time in episode seconds. Null when the syncWord didn't match
   * any Whisper word in the segment's range. */
  timeSec: number | null;
  frame: number | null;
  confidence: number;
}

export interface ManifestSegment {
  id: string;
  type: SegmentType;
  startSec: number;
  endSec: number;
  layer: LayerType;
  beat?: string;
  priority?: string;
  narrationRef?: string;
  asset?: AssetInfo;
  treatment?: TreatmentInfo;
  template?: TemplateInfo;
  hold?: HoldInfo;
  transition?: TransitionInfo;
  layered?: LayeredInfo;
  notes?: string;
  soundCue?: SoundCue;
  soundCueSecondary?: SoundCue;
  textureCues?: TextureCue[];
  /** Frame-accurate sync points resolved by generate_manifest.py from
   * Whisper word timestamps. timeSec is in absolute episode time;
   * ForegroundSegment converts to segment-relative before injecting. */
  syncPoints?: SyncPoint[];
  /** Per-segment direction block from generate_manifest.py (DIR:/PACE: annotations).
   * Merged into data._direction by ForegroundSegment — segment overrides data-file
   * defaults; Whisper syncPoints always win over both. */
  _direction?: Record<string, unknown>;
  /** NLE metadata: seconds of hold to add after this segment in the cut list. */
  holdAfter?: number;
  /** NLE metadata: behaviour during the hold (e.g. "freeze", "loop"). */
  holdBehavior?: string;
  /** NLE metadata: pacing profile key (e.g. "deliberate", "rapid"). */
  paceProfile?: string;
  /** NLE metadata: narration words that trigger the next cut. */
  syncWords?: string[];
  /** NLE metadata: seconds narrator speaks before the visual cut fires (J-cut bridge). */
  narrationLeadIn?: number;
  /** NLE metadata: seconds visual lingers after narration finishes (L-cut bridge). */
  narrationLagOut?: number;
  /** NLE metadata: per-segment render quality overrides forwarded to Lambda. */
  renderQuality?: Record<string, unknown>;
}

export interface NarrationInfo {
  audioFile?: string;
  totalDurationSec: number;
  words?: Array<{ word: string; start: number; end: number }>;
}

export interface BeatInfo {
  id: string;
  title: string;
  startSec: number;
  endSec?: number;
}

export interface MusicBedTrack {
  id: string;
  file: string;
  startSec: number;
  endSec: number;
  fadeInSec?: number;
  fadeOutSec?: number;
  volume: number;
  mood?: "contemplative" | "analytical" | "tension" | "resolution" | "neutral";
  beat?: string;
}

export interface MusicBedConfig {
  tracks: MusicBedTrack[];
}

export interface AssemblyManifest {
  version: string;
  episode: string;
  title?: string;
  fps: number;
  totalDurationSec: number;
  mode: "estimate" | "precise";
  /**
   * Per-episode color emphasis. Mirrors per-typography palette emphasis
   * architecture in tools/recraft/recraft.py for AI-generated content.
   * Wraps the full episode in EpisodeColorEmphasisProvider so all templates
   * inherit the emphasis. Falls back to "neutral" if unset (backward compat).
   * See remotion-templates/BRAND.md → "Per-Episode Color Emphasis".
   */
  episodeColorEmphasis?:
    | "neutral"
    | "soviet"
    | "american-modernist"
    | "chinese-state"
    | "chinese-traditional"
    | "japanese-showa";
  narration: NarrationInfo;
  beats?: BeatInfo[];
  segments: ManifestSegment[];
  /** Episode-level music bed (Layer 1 — continuous ambient tracks). */
  musicBed?: MusicBedConfig;
  /**
   * Episode-level film overlay config. PRESENCE is the activation gate for
   * the per-segment cascade — when absent, no FilmOverlay renders anywhere
   * (preserves dormant behavior for episodes that haven't opted in). When
   * present (even as `{}`), each segment resolves its overlay via
   * `resolveFilmOverlay()` in `src/utils/resolveFilmOverlay.ts`.
   *
   * Shape is `FilmOverlayConfig` (same interface used at segment level above
   * via `TemplateInfo.filmOverlay`). Data-side equivalent:
   * `$defs/filmOverlayConfig` in `data/assembly-manifest.schema.json`.
   */
  filmOverlay?: FilmOverlayConfig;
  /**
   * Visual motif configuration for the episode. When set, the
   * `useMotifProgress()` hook returns a live value in every template segment,
   * letting templates render an evolving geometric identity element across
   * the episode's narrative arc. Optional — omit for episodes with no motif.
   * See `src/hooks/useMotifProgress.tsx` and VISUAL_LANGUAGE.md § "Visual Motifs".
   */
  episodeMotif?: EpisodeMotif;
  /** Episode-level lower-third config. If present, renders LowerThird per beat. */
  lowerThird?: {
    /** Label shown on all lower-thirds, e.g. "∴ PARALLAX · EP.01" */
    label?: string;
    /** Accent color (default: gold) */
    accentColor?: string;
    /** Mode override (default: follows segment bg mode) */
    mode?: "dark" | "light";
    /** Seconds after beat start to show lower-third (default: 0.5) */
    enterDelaySec?: number;
    /** Seconds to show before hiding (default: 4) */
    displayDurationSec?: number;
  };
}

// ── Props ────────────────────────────���────────────────────────────────────────

export interface FullEpisodeProps {
  /** The assembly manifest data (passed as inputProps or loaded inline). */
  manifest: AssemblyManifest;
  /**
   * Map of data file names → loaded JSON data for Remotion templates.
   * Keys are the dataFile values from manifest segments (e.g. "kinetic-92-yield.json").
   * This must be passed in because Remotion can't do dynamic imports at render time.
   */
  templateData: Record<string, any>;
  /**
   * Base path for resolved asset files (footage/images).
   * Assets are resolved as: staticFile(`${assetBasePath}/${segment.asset.file}`)
   */
  assetBasePath?: string;
}

// ── Mood → atmosphere intensity mapping ──────────────────────────────────────

/**
 * Maps the active music bed mood (Layer 1) to a Background atmosphere intensity
 * multiplier. This drives a tension-aware atmospheric overlay so escalation
 * beats feel denser than contemplative beats — without per-template overrides.
 */
const MOOD_INTENSITY: Record<string, number> = {
  contemplative: 0.6,
  analytical: 1.0,
  tension: 1.5,
  resolution: 0.7,
  neutral: 1.0,
};

/**
 * Look up the active music bed track at a given absolute time and return its
 * mood-derived atmosphere intensity. Returns 1.0 if no track is active.
 */
function getAtmosphereIntensityAtTime(
  manifest: AssemblyManifest,
  timeSec: number
): number {
  const tracks = manifest.musicBed?.tracks;
  if (!tracks || tracks.length === 0) return 1.0;
  const containing = tracks.filter(
    (t) => t.startSec <= timeSec && timeSec <= t.endSec
  );
  if (containing.length === 0) return 1.0;
  const active = containing.reduce((best, t) =>
    t.startSec >= best.startSec ? t : best
  );
  return MOOD_INTENSITY[active.mood ?? "neutral"] ?? 1.0;
}

// ── Component map ─────────────────────────────────────────────────────────────

// Composite mode opacity defaults (mirrors BrandImage.tsx COMPOSITE_OPACITY)
const COMPOSITE_DEFAULTS: Record<string, number> = {
  background: 0.35,
  inset: 0.7,
  antipode: 0.45,
  raw: 1.0,
};

export const TEMPLATE_COMPONENTS: Record<string, React.ComponentType<{ data: any }>> = {
  TitleTransition,
  ChoroplethMap,
  KineticTypography,
  // TimelineComparison removed (deprecated; see import-block comment).
  DataChart,
  FrameworkDiagram,
  RouteAnimation,
  DecisionTree,
  OutcomePartition,
  SplitComposition,
  ProbabilityGauge,
  ImageComposite,
  PhotoMontage,
  NetworkDiagram,
  TimeSeriesChart,
  SankeyFlow,
  GameBoard,
  BayesianUpdate,
  StatReveal,
  RadarChart,
  AnnotatedImage,
  EscalationLadder,
  // DualTimeline removed (deprecated; see import-block comment).
  HorizontalTimeline,
  DuelingFrameworks,
  StrategicLandscape,
  ArcDiagram,
  ProportionalSymbolMap,
  Slopegraph,
  KPICard,
  BulletChart,
  StepLine,
  PricingWaterfall,
  AtlasPlate,
  BeeswarmChart,
  BumpChart,
  CalendarHeatmap,
  CartogramMap,
  ConnectedScatterplot,
  DensityMap,
  DumbbellPlot,
  HorizonChart,
  IsotypeChart,
  MarimekkoChart,
  PopulationPyramid,
  RankChangeDotPlot,
  RidgelinePlot,
  Streamgraph,
  TernaryPlot,
  TilegramUSMap,
};

// ── Per-segment FilmOverlay wrapper ──────────────────────────────────────────
//
// Resolves the cascade and wraps children in <FilmOverlay> when episode-level
// `manifest.filmOverlay` is present. When the episode has NOT opted in
// (filmOverlay field absent on the manifest), this renders children directly
// — the whole FilmOverlay system stays dormant, baselines unchanged.
//
// Per-field cascade (see resolveFilmOverlay.ts JSDoc for full chain):
//   1. segment.template.filmOverlay
//   2. backdrop.recommendedPreset (for `preset` only)
//   3. TEMPLATE_PRESET_MAP[componentName] (for `preset` only)
//   4. episodeFilmOverlay
//   5. "documentary" default
//
// IMPORTANT — per-segment time semantics: FilmOverlay uses useCurrentFrame()
// which is sequence-local inside Remotion <Sequence> wrappers. Effects that
// interpolate over `durationInFrames` (light-leak, flicker) cycle PER SEGMENT,
// not per episode. For most presets this is desirable (each archival moment
// gets its own leak punctuation), but it's a semantic change from the
// previous outer-wrap behavior worth flagging.
//
// NOT MEMOIZED — deliberate: React.memo's default shallow equality check
// always fails on `children: ReactNode` because VDOM nodes are new references
// every parent render, meaning the subtree is never actually skip-rendered.
// The only work that would be saved is the resolveFilmOverlay() call (~μs),
// which is insufficient justification. BackgroundSegment and ForegroundSegment
// ARE memoized because they gate expensive SVG-filter and OffthreadVideo
// re-creation; SegmentFilmOverlay has no such heavy work in its own body.

const SegmentFilmOverlay: React.FC<{
  episodeFilmOverlay: FilmOverlayConfig | undefined;
  segmentOverride: FilmOverlayConfig | undefined;
  backdropId: string | undefined;
  componentName: string;
  /** Episode-absolute frame at which this segment starts. Passed to FilmOverlay
   * → LightLeakOverlay so the leak drifts continuously across episode time
   * rather than restarting at each segment boundary. Pass 0 for standalone use. */
  frameOffset: number;
  /** Total episode duration in frames — used as the interpolation ceiling for
   * LightLeakOverlay. Passed through from the manifest totalDurationSec * fps. */
  episodeTotalFrames: number;
  /**
   * Frames over which grain ramps from 0 → resolved intensity at segment start.
   * Derived from the segment's transitionIn type: set to the transition duration
   * for Class B (color-wash) transitions so grain "grows in" with the amber wash
   * rather than snapping to full texture at frame 0.
   * 0 = no ramp (grain at full intensity from frame 0). Default: 0.
   */
  grainRampInFrames?: number;
  children: ReactNode;
}> = ({ episodeFilmOverlay, segmentOverride, backdropId, componentName, frameOffset, episodeTotalFrames, grainRampInFrames = 0, children }) => {
  // GATE: episode has not opted in → render children directly, FilmOverlay
  // dormant. This preserves byte-identical baselines for any episode whose
  // manifest doesn't set `filmOverlay`.
  if (!episodeFilmOverlay) {
    return <>{children}</>;
  }
  const backdrop = backdropId ? backdropMeta(backdropId) : null;
  const resolved = resolveFilmOverlay(
    segmentOverride,
    backdrop,
    componentName,
    episodeFilmOverlay,
  );
  return (
    <FilmOverlay
      effects={resolved.effects}
      intensity={resolved.intensity}
      frameOffset={frameOffset}
      episodeTotalFrames={episodeTotalFrames}
      grainRampInFrames={grainRampInFrames}
    >
      {children}
    </FilmOverlay>
  );
};

// ── Background segment renderer ──────────────────────────────────────────────
// Memoized to prevent SVG filter re-creation on every frame. Each segment
// gets its own BrandImage filter instance, avoiding Chrome throttling when
// multiple video+SVG-filter combos overlap during transitions.
//
// FilmOverlay note: background segments are NOT wrapped in <SegmentFilmOverlay>.
// Most BG windows are covered by a foreground TEMPLATE segment that carries
// its own FilmOverlay wrap (see ForegroundSegment below). Wrapping here too
// caused additive double-treatment (~2× grain, double-dark vignette, two
// overlapping leak cycles) during the bg+fg overlap window — the standard
// case in every manifest. Trade-off: pure-bg breather windows (FOOTAGE/IMAGE
// with no foreground overlay) render without film treatment. If editorial
// review of a real opt-in shows that's wrong, lift the wrap to the parent
// Sequence so each fg+bg pair shares one wrap. Surfaced by review of
// commits 09bb29a (wiring) and 3863b81 (schema).

const BackgroundSegment: React.FC<{
  segment: ManifestSegment;
  assetBasePath: string;
}> = memo(({ segment, assetBasePath }) => {
  const { asset, treatment } = segment;

  // Determine placeholder style based on asset status
  const assetStatus = asset?.status || (asset?.file ? "resolved" : "pending");

  if (assetStatus !== "resolved" || !asset?.file) {
    // Asset not yet sourced (or failed) — render branded placeholder.
    // INTENTIONALLY not wrapped in SegmentFilmOverlay: placeholders and
    // failed-asset markers must stay visually obvious as "needs sourcing."
    // Film treatment (grain, vignette) would visually integrate the warning
    // into the intended look and could cause a reviewer to miss an unsourced
    // asset in an opted-in episode. BackgroundSegment as a whole never wraps
    // (see comment above), so this is already true by construction — noted
    // here to make the editorial intent explicit alongside the failed/pending
    // indicator.
    const placeholderType = asset?.placeholder || "solid-color";
    const bgColor = placeholderType === "solid-color"
      ? (asset?.fallbackColor || palette.paper)
      : palette.paper;

    return (
      <AbsoluteFill
        style={{
          backgroundColor: bgColor,
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
        }}
      >
        <div
          style={{
            color: "#6A6458",
            fontFamily: "IBM Plex Mono, monospace",
            fontSize: 16,
            textAlign: "center",
            padding: layout.spacing.xl,
            maxWidth: 600,
          }}
        >
          <div style={{ fontSize: 28, marginBottom: 8 }}>
            {segment.type === "FOOTAGE" ? "▶" : "▣"}
          </div>
          <div>{asset?.shotListId || asset?.searchTerms?.[0] || segment.id}</div>
          {assetStatus === "failed" && (
            <div style={{ color: semantic.danger, marginTop: 4 }}>ASSET FAILED</div>
          )}
        </div>
      </AbsoluteFill>
    );
  }

  const src = staticFile(`${assetBasePath}/${asset.file}`);
  const ramp = treatment?.ramp || "standard";
  const composite = treatment?.composite || "background";
  const opacity = treatment?.opacity;

  if (segment.type === "FOOTAGE") {
    // Video asset: OffthreadVideo for stable sequential rendering.
    // OffthreadVideo extracts frames outside the main thread, avoiding
    // cache eviction stalls that <Video> hits at 20-30% render progress
    // in long compositions with many short clips.
    return (
      <AbsoluteFill style={{ opacity: opacity ?? COMPOSITE_DEFAULTS[composite] }}>
        <BrandImage
          src="" // BrandImage filter applied to the container; video below
          ramp={ramp}
          composite="raw"
          opacity={1}
        >
          <OffthreadVideo
            src={src}
            style={{
              width: "100%",
              height: "100%",
              objectFit: "cover",
            }}
          />
        </BrandImage>
      </AbsoluteFill>
    );
  }

  // IMAGE — still photo/archival with brand treatment
  return (
    <BrandImage
      src={src}
      ramp={ramp}
      composite={composite}
      opacity={opacity}
    />
  );
});

// ── Foreground segment renderer ──��───────────────────────────────────────────

// Per-segment error boundary. React boundaries must be class components.
// Without this, a single segment that throws at render (malformed data
// passing Zod, off-by-one in template internals, missing dependency) crashes
// the whole 18-min episode render. With it, the broken segment shows a
// visible placeholder and the rest of the episode keeps rendering.

interface SegmentErrorBoundaryProps {
  segmentId: string;
  componentName: string;
  children: ReactNode;
}

class SegmentErrorBoundary extends Component<
  SegmentErrorBoundaryProps,
  { hasError: boolean; message: string }
> {
  constructor(props: SegmentErrorBoundaryProps) {
    super(props);
    this.state = { hasError: false, message: "" };
  }

  static getDerivedStateFromError(error: Error) {
    return { hasError: true, message: error.message };
  }

  componentDidCatch(error: Error, info: ErrorInfo): void {
    // eslint-disable-next-line no-console
    console.error(
      `[FullEpisode] segment ${this.props.segmentId} (${this.props.componentName}) threw at render:`,
      error,
      info.componentStack,
    );
  }

  render(): ReactNode {
    if (this.state.hasError) {
      return (
        <AbsoluteFill
          style={{
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
            backgroundColor: palette.ink,
          }}
        >
          <div
            style={{
              color: semantic.danger,
              fontFamily: "IBM Plex Mono, monospace",
              fontSize: 18,
              textAlign: "center",
              padding: 24,
              maxWidth: 900,
            }}
          >
            ⚠️ {this.props.componentName} threw
            <br />
            <span style={{ fontSize: 13, color: semantic.neutral }}>
              segment {this.props.segmentId}: {this.state.message}
            </span>
          </div>
        </AbsoluteFill>
      );
    }
    return this.props.children;
  }
}

const ForegroundSegment: React.FC<{
  segment: ManifestSegment;
  templateData: Record<string, any>;
  /** Composition fps — needed to convert manifest absolute frames to segment-relative. */
  fps: number;
  manifest: AssemblyManifest;
  /**
   * Frames over which grain ramps in at segment start — derived from the
   * segment's transition-in type by the parent. 0 = no ramp (default).
   * See FilmOverlayProps.grainRampInFrames for the full rationale.
   */
  grainRampInFrames?: number;
}> = memo(({ segment, templateData, fps, manifest, grainRampInFrames = 0 }) => {
  const { template } = segment;

  if (!template?.component) {
    return null;
  }

  const Component = TEMPLATE_COMPONENTS[template.component];
  if (!Component) {
    warnIf(true, "FullEpisode", `Unknown template component "${template.component}" in segment ${segment.id}`);
    return null;
  }

  const data = template.dataFile ? templateData[template.dataFile] : null;
  if (!data && template.dataFile) {
    warnIf(true, "FullEpisode", `Missing template data for "${template.dataFile}" in segment ${segment.id}`);
    // Render placeholder
    return (
      <AbsoluteFill
        style={{
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
        }}
      >
        <div
          style={{
            color: palette.gold,
            fontFamily: "IBM Plex Mono, monospace",
            fontSize: 16,
          }}
        >
          ⚠️ {template.component}: {template.dataFile}
        </div>
      </AbsoluteFill>
    );
  }

  // Build the merged _direction that templates receive via data._direction.
  //
  // Layer order (spread order — later keys override earlier for the same field):
  //   1. data-file _direction — per-template defaults authored in visual-spec
  //   2. segment._direction  — per-beat overrides from DIR:/PACE: manifest annotations
  //   3. syncPoints          — Whisper word timestamps (computed at build time)
  //   4. musicBedAtmosphereMultiplier — injected last; wins over the same key if it were
  //      mistakenly authored in JSON (do not author there — FullEpisode owns this field).
  //
  // When mood is neutral (multiplier 1), the key is omitted so resolveDirection uses ?? 1.
  // When mood ≠ 1 or sync/segment layers exist, merge runs so tension affects atmosphere.
  let dataWithSync = data;
  if (data) {
    const hasSyncPoints = segment.syncPoints && segment.syncPoints.length > 0;
    const hasSegmentDirection =
      segment._direction != null && Object.keys(segment._direction).length > 0;
    const relative = hasSyncPoints
      ? segment.syncPoints!
          .filter((p): p is SyncPoint & { timeSec: number; frame: number } =>
            p.timeSec !== null && p.frame !== null,
          )
          .map((p) => ({
            word: p.word,
            timeSec: p.timeSec - segment.startSec,
            frame: p.frame - Math.round(segment.startSec * fps),
            confidence: p.confidence,
          }))
      : [];

    const moodMult = getAtmosphereIntensityAtTime(manifest, segment.startSec);
    const needsDirectionMerge =
      relative.length > 0 || hasSegmentDirection || moodMult !== 1;

    if (needsDirectionMerge) {
      dataWithSync = {
        ...data,
        _direction: {
          ...(data._direction ?? {}),
          ...(segment._direction ?? {}),
          ...(relative.length > 0 ? { syncPoints: relative } : {}),
          ...(moodMult !== 1 ? { musicBedAtmosphereMultiplier: moodMult } : {}),
        },
      };
    }
  }

  const backdropId = template.backdropId ?? undefined;
  const skipSegmentBackdrop =
    segment.layered != null || template.component === "TitleTransition";
  const backdropKnown =
    backdropId != null &&
    backdropId.length > 0 &&
    backdropStaticFile(backdropId) != null;

  warnIf(
    Boolean(
      backdropId &&
        backdropId.length > 0 &&
        !backdropKnown &&
        !skipSegmentBackdrop,
    ),
    "FullEpisode",
    `Unknown template.backdropId "${backdropId}" in segment ${segment.id} — available: ${BACKDROP_MANIFEST.map((b) => b.id).join(", ")}`,
  );

  const showSegmentBackdrop =
    Boolean(backdropKnown && !skipSegmentBackdrop);

  // Templates use opaque light Background by default — paper hides SegmentBackdrop.
  // Punch through for non-title segments when this row has template.backdropId.
  const dataForTemplate =
    showSegmentBackdrop &&
    dataWithSync &&
    template.component !== "TitleTransition"
      ? { ...dataWithSync, transparentBackground: true as const }
      : dataWithSync;

  // Editorial mode is FULLY DERIVED from the active backdrop's register
  // (light vs dark), with `light` as the safe default when no backdrop is
  // set or the manifest lookup misses. Any EditorialFrame in the subtree
  // picks this up via context — no per-segment script tag, no episode
  // toggle. See src/design/editorialModes.ts § modeFromBackdropRegister.
  const editorialMode = modeFromBackdropRegister(
    backdropId && backdropKnown ? backdropMeta(backdropId)?.register : undefined,
  );

  return (
    <SegmentErrorBoundary
      segmentId={segment.id}
      componentName={template.component}
    >
      <SegmentMotifProgressProvider segmentStartSec={segment.startSec}>
      <SegmentFilmOverlay
        episodeFilmOverlay={manifest.filmOverlay}
        segmentOverride={template.filmOverlay}
        backdropId={backdropId}
        componentName={template.component}
        frameOffset={Math.round(segment.startSec * fps)}
        episodeTotalFrames={Math.round(manifest.totalDurationSec * manifest.fps)}
        grainRampInFrames={grainRampInFrames}
      >
        <EditorialModeProvider mode={editorialMode}>
          <AbsoluteFill>
            {showSegmentBackdrop && backdropId ? (
              <SegmentBackdrop backdropId={backdropId} />
            ) : null}
            <AbsoluteFill style={{ zIndex: 1 }}>
              <Component data={dataForTemplate} />
            </AbsoluteFill>
          </AbsoluteFill>
        </EditorialModeProvider>
      </SegmentFilmOverlay>
      </SegmentMotifProgressProvider>
    </SegmentErrorBoundary>
  );
});

// ── Beat flash (replaces @remotion/light-leaks) ──────────────────────────────
//
// @remotion/light-leaks uses a WebGL canvas and hard-crashes with cancelRender()
// when headless Chromium can't get a WebGL context (the default on macOS without
// --gl=angle). This CSS-based radial burst achieves the same film-burn look
// with zero GPU dependencies — interpolated opacity + radial-gradient + screen
// blend mode produces an identical cinematic beat-boundary flash.

const BeatFlash: React.FC<{ durationInFrames: number; hueShift: number }> = ({
  durationInFrames,
  hueShift,
}) => {
  const frame = useCurrentFrame();
  // linear-ok: 4-keyframe asymmetric envelope (fast in / hold / slow out) — easing is in the keyframe spacing
  const opacity = interpolate(
    frame,
    [
      0,
      Math.round(durationInFrames * 0.2),
      Math.round(durationInFrames * 0.5),
      durationInFrames,
    ],
    [0, 0.65, 0.35, 0],
    { extrapolateLeft: "clamp", extrapolateRight: "clamp" }
  );

  // Base hue: amber (~38°). hueShift rotates: rose (−25°), cyan (+30°), warm (−10°)
  const hue = 38 + hueShift;
  return (
    <AbsoluteFill
      style={{
        background: `radial-gradient(ellipse 80% 60% at 42% 38%,
          hsla(${hue}, 90%, 88%, 0.95) 0%,
          hsla(${hue}, 75%, 65%, 0.55) 35%,
          transparent 70%)`,
        opacity,
        mixBlendMode: "screen",
        pointerEvents: "none",
      }}
    />
  );
};

// ── Main composition ──────────────────────────────────────────────────────────

export const FullEpisode: React.FC<FullEpisodeProps> = ({
  manifest,
  templateData,
  assetBasePath = "assets",
}) => {
  const { fps } = useVideoConfig();

  // Split segments into layers + build index for layered lookups.
  //
  // HOLD segments are merged into the preceding non-HOLD segment of the same
  // layer by extending that segment's endSec. The HOLD itself is dropped from
  // the rendering list. Effect: the previous visual sustains through the HOLD
  // window — for FOOTAGE the video keeps playing, for TEMPLATE the template
  // animation continues past its natural end (interpolate's clamp behavior
  // typically holds the final state). True last-frame freeze (per the
  // schema's `freeze: true` semantic) is approximated by extension; capturing
  // and re-rendering the literal last frame would require frame-state
  // snapshotting, deferred until the extension behavior proves insufficient.
  // Without this preprocessing HOLD segments fall through to BackgroundSegment
  // (which renders the asset-pending placeholder) or ForegroundSegment (which
  // renders nothing) — neither sustains the previous visual.
  const { backgroundSegs, foregroundSegs, segmentIndex } = useMemo(() => {
    const bg: ManifestSegment[] = [];
    const fg: ManifestSegment[] = [];
    const idx: Record<string, ManifestSegment> = {};

    // Pass 1: build per-layer ordered lists, indexing by id. HOLD segments
    // are routed to their layer like any other segment — pass 2 below
    // collapses them into the preceding non-HOLD on that layer.
    for (const seg of manifest.segments) {
      idx[seg.id] = seg;
      if (seg.layer === "foreground") {
        fg.push(seg);
      } else {
        bg.push(seg);
      }
    }

    // Pass 2: per layer, walk the ordered list and merge HOLDs into the
    // preceding non-HOLD by extending its endSec. Drop the HOLD itself.
    // Sort defensively in case the manifest isn't in time order.
    const mergeHolds = (segs: ManifestSegment[]): ManifestSegment[] => {
      const sorted = segs.slice().sort((a, b) => a.startSec - b.startSec);
      const out: ManifestSegment[] = [];
      for (const seg of sorted) {
        if (seg.type === "HOLD") {
          if (out.length === 0) {
            // HOLD with nothing before it on this layer — log and drop.
            // Without a preceding visual to sustain, it would render as a
            // placeholder; dropping it leaves a transparent gap, which is
            // strictly preferable.
            // Use `warnIf` (not `console.warn`) because this useMemo can
            // re-run on prop changes, and Remotion renders every frame —
            // a raw console.warn would fire 30×/sec under prop churn.
            // warnIf dedupes by (template, message) tuple per session.
            warnIf(
              true,
              "FullEpisode",
              `HOLD segment ${seg.id} has no preceding segment on layer "${seg.layer}" to sustain. Dropping.`,
            );
            continue;
          }
          // Extend the preceding segment's endSec to cover this HOLD window.
          // Replace the last entry with a copy carrying the extended end so
          // we don't mutate the input manifest.
          const prev = out[out.length - 1];
          out[out.length - 1] = { ...prev, endSec: Math.max(prev.endSec, seg.endSec) };
        } else {
          out.push(seg);
        }
      }
      return out;
    };

    const bgMerged = mergeHolds(bg);
    const fgMerged = mergeHolds(fg);

    // Identify background segments claimed by layered foregrounds —
    // these are rendered inside LayeredComposition, not standalone.
    // Note: this runs against the post-merge fg list; layered-bg references
    // by id still resolve via segmentIndex which holds the original (pre-
    // merge) segment objects.
    const claimedBgIds = new Set<string>();
    for (const seg of fgMerged) {
      if (seg.layered?.backgroundSegmentId) {
        claimedBgIds.add(seg.layered.backgroundSegmentId);
      }
    }

    const standaloneBg = bgMerged.filter((s) => !claimedBgIds.has(s.id));

    return {
      backgroundSegs: standaloneBg,
      foregroundSegs: fgMerged,
      segmentIndex: idx,
    };
  }, [manifest.segments]);

  // Extract audio cues from all segments for AudioLayer
  const segmentAudio = useMemo(() => {
    return manifest.segments
      .filter((seg) => seg.soundCue || seg.soundCueSecondary || (seg.textureCues && seg.textureCues.length > 0))
      .map((seg) => ({
        segmentId: seg.id,
        startSec: seg.startSec,
        soundCue: seg.soundCue,
        soundCueSecondary: seg.soundCueSecondary,
        textureCues: seg.textureCues,
      }));
  }, [manifest.segments]);

  // Extract segment timeline for music-bed ducking in AudioLayer.
  // All segments (not just those with audio cues) are included so the ducking
  // curve has full coverage across the episode — FOOTAGE/HOLD segments lift the
  // music even if they carry no SFX of their own.
  const segmentTimeline = useMemo((): SegmentTimeline[] => {
    return manifest.segments.map((seg) => ({
      startSec: seg.startSec,
      endSec:   seg.endSec,
      // No cast: TypeScript verifies SegmentType satisfies SegmentTimeline["type"].
      // If a new SegmentType is added without updating SegmentTimeline, this line
      // becomes a compile error — keeping the two unions in sync automatically.
      type: seg.type,
    }));
  }, [manifest.segments]);

  const lowerThirdConfig = manifest.lowerThird;

  // Build visual layers (shared between overlay and non-overlay paths)
  const visualLayers = (
    <>
      {/* Layer 1: Background segments (footage, images) */}
      {backgroundSegs.map((seg) => {
        const startFrame = Math.round(seg.startSec * fps);
        const durationFrames = Math.round((seg.endSec - seg.startSec) * fps);

        if (durationFrames <= 0) return null;

        return (
          <Sequence
            key={seg.id}
            from={startFrame}
            durationInFrames={durationFrames}
            name={`bg-${seg.id}`}
          >
            <SegmentErrorBoundary
              segmentId={seg.id}
              componentName={seg.type}
            >
              <TransitionWrapper
                transitionIn={seg.transition?.in}
                transitionOut={seg.transition?.out}
                durationSec={seg.transition?.durationSec}
                washColor={seg.transition?.washColor}
                durationInFrames={durationFrames}
              >
                <BackgroundSegment
                  segment={seg}
                  assetBasePath={assetBasePath}
                />
              </TransitionWrapper>
            </SegmentErrorBoundary>
          </Sequence>
        );
      })}

      {/* Layer 2: Foreground segments (templates, transitions, layered) */}
      {foregroundSegs.map((seg) => {
        const startFrame = Math.round(seg.startSec * fps);
        const durationFrames = Math.round((seg.endSec - seg.startSec) * fps);

        if (durationFrames <= 0) return null;

        // Layered mode: foreground template composited over a background segment
        const layeredBgId = seg.layered?.backgroundSegmentId;
        const layeredBg = layeredBgId ? (segmentIndex[layeredBgId] ?? null) : null;
        warnIf(
          !!layeredBgId && !layeredBg,
          "FullEpisode",
          `Layered segment ${seg.id} references backgroundSegmentId "${layeredBgId}" which was not found in the manifest.`
        );

        return (
          <Sequence
            key={seg.id}
            from={startFrame}
            durationInFrames={durationFrames}
            name={layeredBg ? `layered-${seg.id}` : `fg-${seg.id}`}
          >
            <TransitionWrapper
              transitionIn={seg.transition?.in}
              transitionOut={seg.transition?.out}
              durationSec={seg.transition?.durationSec}
              washColor={seg.transition?.washColor}
              durationInFrames={durationFrames}
            >
              {layeredBg ? (
                <LayeredComposition
                  position={seg.layered?.position}
                  blendMode={seg.layered?.blendMode}
                  foregroundOpacity={seg.layered?.foregroundOpacity}
                  backgroundDim={seg.layered?.backgroundDim}
                  foregroundFadeInSec={seg.layered?.foregroundFadeInSec}
                  vignette={seg.layered?.vignette}
                >
                  {/* Fresh {background, foreground} object literal per frame —
                      defeats React.memo if LayeredComposition is ever memoized
                      (it isn't today; flagged by May-17 perf audit). When
                      memoizing LayeredComposition: switch to separate
                      `backgroundSlot` / `foregroundSlot` props so the object
                      literal goes away. */}
                  {{
                    background: (
                      <SegmentErrorBoundary
                        segmentId={layeredBg.id}
                        componentName={layeredBg.type}
                      >
                        <BackgroundSegment
                          segment={layeredBg}
                          assetBasePath={assetBasePath}
                        />
                      </SegmentErrorBoundary>
                    ),
                    foreground: (
                      <ForegroundSegment
                        segment={seg}
                        templateData={templateData}
                        fps={fps}
                        manifest={manifest}
                        grainRampInFrames={
                          seg.transition?.in === "color-wash"
                            ? Math.round((seg.transition?.durationSec ?? 0.7) * fps)
                            : 0
                        }
                      />
                    ),
                  }}
                </LayeredComposition>
              ) : (
                <ForegroundSegment
                  segment={seg}
                  templateData={templateData}
                  fps={fps}
                  manifest={manifest}
                  grainRampInFrames={
                    // Class B transition (Remotion ↔ grainy pillar): ramp grain
                    // in over the color-wash window so texture "grows into" the
                    // amber flood rather than snapping to full intensity at frame 0.
                    // For dissolve/fade transitions the TransitionWrapper's opacity
                    // already fades grain smoothly; the ramp is additive but subtle.
                    // For cut transitions there's no wrapper fade, so this is the
                    // only grain introduction mechanism.
                    seg.transition?.in === "color-wash"
                      ? Math.round((seg.transition?.durationSec ?? 0.7) * fps)
                      : 0
                  }
                />
              )}
            </TransitionWrapper>
          </Sequence>
        );
      })}

      {/* Layer 3: Section indicator (persistent beat label) */}
      {manifest.beats && manifest.beats.length > 0 && (
        <SectionIndicator beats={manifest.beats} />
      )}

      {/* Layer 4: Lower-thirds (one per beat, driven by manifest) */}
      {lowerThirdConfig && manifest.beats && manifest.beats.map((beat) => {
        const enterDelay = lowerThirdConfig.enterDelaySec ?? 0.5;
        const displayDuration = lowerThirdConfig.displayDurationSec ?? 4;
        const enterFrame = Math.round((beat.startSec + enterDelay) * fps);
        const exitFrame = Math.round((beat.startSec + enterDelay + displayDuration) * fps);

        return (
          <Sequence
            key={`lt-${beat.id}`}
            from={0}
            durationInFrames={Math.round(manifest.totalDurationSec * fps)}
            name={`lower-third-${beat.id}`}
          >
            <LowerThird
              label={lowerThirdConfig.label}
              title={beat.title}
              mode={lowerThirdConfig.mode || "dark"}
              accentColor={lowerThirdConfig.accentColor}
              enterFrame={enterFrame}
              exitFrame={exitFrame}
            />
          </Sequence>
        );
      })}

      {/* Layer 4b: Beat-boundary film-burn flash.
          One BeatFlash per beat (skipping the first), 1.0s centered on the beat boundary.
          Hue shifts gently per beat for variety. Pure CSS — no WebGL required. */}
      {manifest.beats && manifest.beats.slice(1).map((beat, idx) => {
        const burnDurationSec = 1.0;
        const startFrame = Math.round((beat.startSec - burnDurationSec * 0.3) * fps);
        const durationInFrames = Math.round(burnDurationSec * fps);
        // Rotate hue per beat: amber-warm → rose → cyan-cool → amber
        const hueShifts = [0, -25, 30, -10];
        const hueShift = hueShifts[idx % hueShifts.length];
        return (
          <Sequence
            key={`flash-${beat.id}`}
            from={Math.max(0, startFrame)}
            durationInFrames={durationInFrames}
            name={`beat-flash-${beat.id}`}
          >
            <BeatFlash durationInFrames={durationInFrames} hueShift={hueShift} />
          </Sequence>
        );
      })}
    </>
  );

  return (
    <EpisodeMotifProvider
      motif={manifest.episodeMotif}
      totalDurationSec={manifest.totalDurationSec}
    >
    <EpisodeColorEmphasisProvider value={manifest.episodeColorEmphasis}>
      {/*
       * EditorialSurface provides the paper background + grain layer that
       * unifies Remotion analytical content with the AI-generated illustration
       * pillar. Replaces the former hardcoded backgroundColor: "#F5F0E8".
       * Intensity 0.6 = "felt, not seen" — warmth before texture.
       */}
      <EditorialSurface intensity={0.6}>
        {/*
         * FilmOverlay was previously wrapped here at the outer-composition
         * level (single instance for the whole video). As of the per-segment
         * cascade landing, each BackgroundSegment / ForegroundSegment wraps
         * its own content via <SegmentFilmOverlay>, gated on
         * `manifest.filmOverlay` being present. EditorialSurface stays at
         * the outer level — paper background + grain are episode-wide.
         *
         * `filmOverlayConfig` is no longer consumed here; kept on the
         * manifest type as the activation gate + cascade fallback layer 4.
         */}
        {visualLayers}

        {/* Audio layers (always outside film overlay — audio isn't visual) */}

        {/* Layer 5: Narration (dominant — -0dB reference) */}
        {manifest.narration.audioFile && (
          <Audio
            src={staticFile(
              `episodes/${manifest.episode.toLowerCase()}/${manifest.narration.audioFile}`
            )}
          />
        )}

        {/* Layers 6-8: Music bed + transition SFX + texture hits */}
        <AudioLayer
          episode={manifest.episode.toLowerCase()}
          musicBedTracks={manifest.musicBed?.tracks}
          segmentAudio={segmentAudio}
          segmentTimeline={segmentTimeline}
        />
      </EditorialSurface>
    </EpisodeColorEmphasisProvider>
    </EpisodeMotifProvider>
  );
};

// ── Metadata calculator ───────────────────────────────────────────────────────

/**
 * calculateMetadata for Composition registration.
 * Reads totalDurationSec from the manifest and converts to frames.
 */
export function calculateFullEpisodeMetadata({
  props,
}: {
  props: FullEpisodeProps;
}) {
  const totalFrames = Math.ceil(props.manifest.totalDurationSec * props.manifest.fps);

  return {
    durationInFrames: totalFrames,
    fps: props.manifest.fps,
    width: layout.width,
    height: layout.height,
  };
}
