/**
 * FullEpisode — Assembly-manifest-driven episode composition.
 *
 * Replaces the manual SiliconTrap.tsx approach (27-clip Series) with a data-driven
 * composition that renders the COMPLETE video: narration audio, motion graphics,
 * stock footage with brand treatment, and transitions — all from one JSON file.
 *
 * Architecture:
 *   - Reads an assembly manifest (generated by tools/assembly/generate_manifest.py)
 *   - Bottom layer: background segments (FOOTAGE, IMAGE) with BrandImage treatment
 *   - Top layer: foreground segments (TEMPLATE, TRANSITION) positioned by timestamp
 *   - Audio layer: narration track via Remotion <Audio>
 *   - HOLD segments sustain the previous visual with an optional freeze
 *
 * Usage:
 *   Register as a Composition with the manifest as defaultProps or inputProps:
 *
 *   <Composition
 *     id="silicon-trap-full"
 *     component={FullEpisode}
 *     calculateMetadata={calculateFullEpisodeMetadata}
 *     defaultProps={{ manifestPath: "episodes/silicon-trap/assembly-manifest.json" }}
 *   />
 *
 * Then render:
 *   npx remotion render silicon-trap-full out/silicon-trap-full.mp4
 *
 * Render performance notes (from research):
 *   - Uses <OffthreadVideo> instead of <Video> for stock footage segments.
 *     Extracts frames off-thread, preventing cache eviction stalls that hit
 *     at 20-30% progress in long compositions with many short clips.
 *   - BackgroundSegment and ForegroundSegment are memoized to prevent
 *     SVG filter re-creation per frame (Chrome throttles overlapping video+SVG).
 *   - For Lambda: use memorySizeInMb: 3008 and concurrency: 4.
 *     18 min @ 1080p30 renders in ~2-5 min, well within the 5 GB file limit.
 */

import React, { useMemo, memo, Component, type ReactNode, type ErrorInfo } from "react";
import {
  AbsoluteFill,
  Audio,
  OffthreadVideo,
  Sequence,
  staticFile,
  useVideoConfig,
} from "remotion";
import { LightLeak } from "@remotion/light-leaks";
import { layout } from "../../design/theme";
import { BrandImage } from "../../components/BrandImage";
import { SectionIndicator } from "../../components/SectionIndicator";
import {
  TransitionWrapper,
  type TransitionType,
} from "../../components/Transitions";
import { LayeredComposition } from "../../components/LayeredComposition";
import { LowerThird } from "../../components/LowerThird";
import { FilmOverlay } from "../../components/FilmOverlay";
import { AudioLayer } from "../../components/AudioLayer";
import { EpisodeColorEmphasisProvider } from "../../hooks/useEpisodeColorEmphasis";
import { EditorialSurface } from "../../components/EditorialSurface";

// ── Template imports ─��────────────────────────────────────────────────────────

import { TitleTransition } from "../TitleTransition/TitleTransition";
import { ChoroplethMap } from "../ChoroplethMap/ChoroplethMap";
import { KineticTypography } from "../KineticTypography/KineticTypography";
import { TimelineComparison } from "../TimelineComparison/TimelineComparison";
import { DataChart } from "../DataChart/DataChart";
import { FrameworkDiagram } from "../FrameworkDiagram/FrameworkDiagram";
import { RouteAnimation } from "../RouteAnimation/RouteAnimation";
import { DecisionTree } from "../DecisionTree/DecisionTree";
import { SplitComposition } from "../SplitComposition/SplitComposition";
import { ProbabilityGauge } from "../ProbabilityGauge/ProbabilityGauge";
import { ImageComposite } from "../ImageComposite/ImageComposite";
import { PhotoMontage } from "../PhotoMontage/PhotoMontage";
import { NetworkDiagram } from "../NetworkDiagram/NetworkDiagram";
import { TimeSeriesChart } from "../TimeSeriesChart/TimeSeriesChart";
import { SankeyFlow } from "../SankeyFlow/SankeyFlow";
import { GameBoard } from "../GameBoard/GameBoard";
import { BayesianUpdate } from "../BayesianUpdate/BayesianUpdate";
import { StatReveal } from "../StatReveal/StatReveal";
import { RadarChart } from "../RadarChart/RadarChart";
import { AnnotatedImage } from "../AnnotatedImage/AnnotatedImage";
import { EscalationLadder } from "../EscalationLadder/EscalationLadder";
import { DualTimeline } from "../DualTimeline/DualTimeline";
import { HorizontalTimeline } from "../HorizontalTimeline/HorizontalTimeline";
import { warnIf } from "../../utils/dataWarnings";

// ── Types ──────���─────────────────────────────��────────────────────────────────

type SegmentType = "FOOTAGE" | "IMAGE" | "TEMPLATE" | "TRANSITION" | "HOLD";
type LayerType = "background" | "foreground";
type DuotoneRamp = "standard" | "conflict" | "editorial";
type CompositeMode = "background" | "inset" | "antipode" | "raw";
// TransitionType imported from ../../components/Transitions

interface AssetInfo {
  shotListId?: string;
  searchTerms?: string[];
  source?: string;
  file?: string;
  status?: "pending" | "resolved" | "failed";
  placeholder?: "solid-color" | "last-frame";
  fallbackColor?: string;
}

interface TreatmentInfo {
  ramp?: DuotoneRamp;
  composite?: CompositeMode;
  opacity?: number;
}

interface TemplateInfo {
  component: string;
  dataFile?: string;
}

interface HoldInfo {
  freeze?: boolean;
}

interface TransitionInfo {
  in?: TransitionType;
  out?: TransitionType;
  durationSec?: number;
}

interface LayeredInfo {
  /** ID of the background segment this foreground composites over */
  backgroundSegmentId: string;
  /** Foreground position preset */
  position?: "full" | "lower-third" | "upper-third" | "center-inset" | "bottom-bar";
  /** Blend mode for the foreground */
  blendMode?: "normal" | "multiply" | "screen" | "overlay" | "soft-light";
  /** Foreground opacity 0-1 */
  foregroundOpacity?: number;
  /** Background dim amount 0-1 */
  backgroundDim?: number;
  /** Foreground fade-in duration in seconds */
  foregroundFadeInSec?: number;
  /** Show vignette overlay */
  vignette?: boolean;
}

interface SoundCue {
  type:
    | "beat-transition"
    | "stat-reveal"
    | "tension-rise"
    | "tension-resolve"
    | "map-whoosh"
    | "quote-bell"
    | "section-open"
    | "end-stinger";
  offsetSec?: number;
  intensity?: "subtle" | "normal" | "dramatic";
}

interface TextureCue {
  type:
    | "dot-click"
    | "card-settle"
    | "line-draw"
    | "region-glow"
    | "bar-grow"
    | "node-pop"
    | "page-turn";
  offsetSec: number;
  volume?: number;
  label?: string;
}

interface SyncPoint {
  word: string;
  /** Absolute time in episode seconds. Null when the syncWord didn't match
   * any Whisper word in the segment's range. */
  timeSec: number | null;
  frame: number | null;
  confidence: number;
}

interface ManifestSegment {
  id: string;
  type: SegmentType;
  startSec: number;
  endSec: number;
  layer: LayerType;
  beat?: string;
  priority?: string;
  narrationRef?: string;
  asset?: AssetInfo;
  treatment?: TreatmentInfo;
  template?: TemplateInfo;
  hold?: HoldInfo;
  transition?: TransitionInfo;
  layered?: LayeredInfo;
  notes?: string;
  soundCue?: SoundCue;
  soundCueSecondary?: SoundCue;
  textureCues?: TextureCue[];
  /** Frame-accurate sync points resolved by generate_manifest.py from
   * Whisper word timestamps. timeSec is in absolute episode time;
   * ForegroundSegment converts to segment-relative before injecting. */
  syncPoints?: SyncPoint[];
}

interface NarrationInfo {
  audioFile?: string;
  totalDurationSec: number;
  words?: Array<{ word: string; start: number; end: number }>;
}

interface BeatInfo {
  id: string;
  title: string;
  startSec: number;
  endSec?: number;
}

interface MusicBedTrack {
  id: string;
  file: string;
  startSec: number;
  endSec: number;
  fadeInSec?: number;
  fadeOutSec?: number;
  volume: number;
  mood?: "contemplative" | "analytical" | "tension" | "resolution" | "neutral";
  beat?: string;
}

interface MusicBedConfig {
  tracks: MusicBedTrack[];
}

interface AssemblyManifest {
  version: string;
  episode: string;
  title?: string;
  fps: number;
  totalDurationSec: number;
  mode: "estimate" | "precise";
  /**
   * Per-episode color emphasis. Mirrors per-typography palette emphasis
   * architecture in tools/recraft/recraft.py for AI-generated content.
   * Wraps the full episode in EpisodeColorEmphasisProvider so all templates
   * inherit the emphasis. Falls back to "neutral" if unset (backward compat).
   * See remotion-templates/BRAND.md → "Per-Episode Color Emphasis".
   */
  episodeColorEmphasis?:
    | "neutral"
    | "soviet"
    | "american-modernist"
    | "chinese-state"
    | "chinese-traditional"
    | "japanese-showa";
  narration: NarrationInfo;
  beats?: BeatInfo[];
  segments: ManifestSegment[];
  /** Episode-level music bed (Layer 1 — continuous ambient tracks). */
  musicBed?: MusicBedConfig;
  /** Episode-level film overlay config. Wraps all visual layers. */
  filmOverlay?: {
    effects?: Array<"grain" | "vignette" | "light-leak" | "dust" | "scratch" | "flicker">;
    intensity?: number;
  };
  /** Episode-level lower-third config. If present, renders LowerThird per beat. */
  lowerThird?: {
    /** Label shown on all lower-thirds, e.g. "∴ PARALLAX · EP.01" */
    label?: string;
    /** Accent color (default: gold) */
    accentColor?: string;
    /** Mode override (default: follows segment bg mode) */
    mode?: "dark" | "light";
    /** Seconds after beat start to show lower-third (default: 0.5) */
    enterDelaySec?: number;
    /** Seconds to show before hiding (default: 4) */
    displayDurationSec?: number;
  };
}

// ── Props ────────────────────────────���────────────────────────────────────────

interface FullEpisodeProps {
  /** The assembly manifest data (passed as inputProps or loaded inline). */
  manifest: AssemblyManifest;
  /**
   * Map of data file names → loaded JSON data for Remotion templates.
   * Keys are the dataFile values from manifest segments (e.g. "kinetic-92-yield.json").
   * This must be passed in because Remotion can't do dynamic imports at render time.
   */
  templateData: Record<string, any>;
  /**
   * Base path for resolved asset files (footage/images).
   * Assets are resolved as: staticFile(`${assetBasePath}/${segment.asset.file}`)
   */
  assetBasePath?: string;
}

// ── Mood → atmosphere intensity mapping ──────────────────────────────────────

/**
 * Maps the active music bed mood (Layer 1) to a Background atmosphere intensity
 * multiplier. This drives a tension-aware atmospheric overlay so escalation
 * beats feel denser than contemplative beats — without per-template overrides.
 */
const MOOD_INTENSITY: Record<string, number> = {
  contemplative: 0.6,
  analytical: 1.0,
  tension: 1.5,
  resolution: 0.7,
  neutral: 1.0,
};

/**
 * Look up the active music bed track at a given absolute time and return its
 * mood-derived atmosphere intensity. Returns 1.0 if no track is active.
 */
function getAtmosphereIntensityAtTime(
  manifest: AssemblyManifest,
  timeSec: number
): number {
  const tracks = manifest.musicBed?.tracks;
  if (!tracks || tracks.length === 0) return 1.0;
  // Find the latest-starting track that contains this timestamp
  let active = tracks[0];
  for (const t of tracks) {
    if (t.startSec <= timeSec && timeSec <= t.endSec && t.startSec >= active.startSec) {
      active = t;
    }
  }
  return MOOD_INTENSITY[active.mood ?? "neutral"] ?? 1.0;
}

// ── Component map ─────────────────────────────────────────────────────────────

// Composite mode opacity defaults (mirrors BrandImage.tsx COMPOSITE_OPACITY)
const COMPOSITE_DEFAULTS: Record<string, number> = {
  background: 0.35,
  inset: 0.7,
  antipode: 0.45,
  raw: 1.0,
};

const TEMPLATE_COMPONENTS: Record<string, React.ComponentType<{ data: any }>> = {
  TitleTransition,
  ChoroplethMap,
  KineticTypography,
  TimelineComparison,
  DataChart,
  FrameworkDiagram,
  RouteAnimation,
  DecisionTree,
  SplitComposition,
  ProbabilityGauge,
  ImageComposite,
  PhotoMontage,
  NetworkDiagram,
  TimeSeriesChart,
  SankeyFlow,
  GameBoard,
  BayesianUpdate,
  StatReveal,
  RadarChart,
  AnnotatedImage,
  EscalationLadder,
  DualTimeline,
  HorizontalTimeline,
};

// ── Background segment renderer ──────────────────────────────────────────────
// Memoized to prevent SVG filter re-creation on every frame. Each segment
// gets its own BrandImage filter instance, avoiding Chrome throttling when
// multiple video+SVG-filter combos overlap during transitions.

const BackgroundSegment: React.FC<{
  segment: ManifestSegment;
  assetBasePath: string;
}> = memo(({ segment, assetBasePath }) => {
  const { asset, treatment } = segment;

  // Determine placeholder style based on asset status
  const assetStatus = asset?.status || (asset?.file ? "resolved" : "pending");

  if (assetStatus !== "resolved" || !asset?.file) {
    // Asset not yet sourced — render branded placeholder
    const placeholderType = asset?.placeholder || "solid-color";
    const bgColor = placeholderType === "solid-color"
      ? (asset?.fallbackColor || "#F5F0E8")
      : "#F5F0E8";

    return (
      <AbsoluteFill
        style={{
          backgroundColor: bgColor,
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
        }}
      >
        <div
          style={{
            color: "#6A6458",
            fontFamily: "IBM Plex Mono, monospace",
            fontSize: 16,
            textAlign: "center",
            padding: layout.spacing.xl,
            maxWidth: 600,
          }}
        >
          <div style={{ fontSize: 28, marginBottom: 8 }}>
            {segment.type === "FOOTAGE" ? "▶" : "▣"}
          </div>
          <div>{asset?.shotListId || asset?.searchTerms?.[0] || segment.id}</div>
          {assetStatus === "failed" && (
            <div style={{ color: "#C23B22", marginTop: 4 }}>ASSET FAILED</div>
          )}
        </div>
      </AbsoluteFill>
    );
  }

  const src = staticFile(`${assetBasePath}/${asset.file}`);
  const ramp = treatment?.ramp || "standard";
  const composite = treatment?.composite || "background";
  const opacity = treatment?.opacity;

  if (segment.type === "FOOTAGE") {
    // Video asset: OffthreadVideo for stable sequential rendering.
    // OffthreadVideo extracts frames outside the main thread, avoiding
    // cache eviction stalls that <Video> hits at 20-30% render progress
    // in long compositions with many short clips.
    return (
      <AbsoluteFill style={{ opacity: opacity ?? COMPOSITE_DEFAULTS[composite] }}>
        <BrandImage
          src="" // BrandImage filter applied to the container; video below
          ramp={ramp as any}
          composite="raw"
          opacity={1}
        >
          <OffthreadVideo
            src={src}
            style={{
              width: "100%",
              height: "100%",
              objectFit: "cover",
            }}
          />
        </BrandImage>
      </AbsoluteFill>
    );
  }

  // IMAGE — still photo/archival with brand treatment
  return (
    <BrandImage
      src={src}
      ramp={ramp as any}
      composite={composite as any}
      opacity={opacity}
    />
  );
});

// ── Foreground segment renderer ──��───────────────────────────────────────────

// Per-segment error boundary. React boundaries must be class components.
// Without this, a single segment that throws at render (malformed data
// passing Zod, off-by-one in template internals, missing dependency) crashes
// the whole 18-min episode render. With it, the broken segment shows a
// visible placeholder and the rest of the episode keeps rendering.

interface SegmentErrorBoundaryProps {
  segmentId: string;
  componentName: string;
  children: ReactNode;
}

class SegmentErrorBoundary extends Component<
  SegmentErrorBoundaryProps,
  { hasError: boolean; message: string }
> {
  constructor(props: SegmentErrorBoundaryProps) {
    super(props);
    this.state = { hasError: false, message: "" };
  }

  static getDerivedStateFromError(error: Error) {
    return { hasError: true, message: error.message };
  }

  componentDidCatch(error: Error, info: ErrorInfo): void {
    // eslint-disable-next-line no-console
    console.error(
      `[FullEpisode] segment ${this.props.segmentId} (${this.props.componentName}) threw at render:`,
      error,
      info.componentStack,
    );
  }

  render(): ReactNode {
    if (this.state.hasError) {
      return (
        <AbsoluteFill
          style={{
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
            backgroundColor: "#1C1814",
          }}
        >
          <div
            style={{
              color: "#A64D46",
              fontFamily: "IBM Plex Mono, monospace",
              fontSize: 18,
              textAlign: "center",
              padding: 24,
              maxWidth: 900,
            }}
          >
            ⚠️ {this.props.componentName} threw
            <br />
            <span style={{ fontSize: 13, color: "#888780" }}>
              segment {this.props.segmentId}: {this.state.message}
            </span>
          </div>
        </AbsoluteFill>
      );
    }
    return this.props.children;
  }
}

const ForegroundSegment: React.FC<{
  segment: ManifestSegment;
  templateData: Record<string, any>;
  /** Composition fps — needed to convert manifest absolute frames to segment-relative. */
  fps: number;
}> = memo(({ segment, templateData, fps }) => {
  const { template } = segment;

  if (!template?.component) {
    return null;
  }

  const Component = TEMPLATE_COMPONENTS[template.component];
  if (!Component) {
    warnIf(true, "FullEpisode", `Unknown template component "${template.component}" in segment ${segment.id}`);
    return null;
  }

  const data = template.dataFile ? templateData[template.dataFile] : null;
  if (!data && template.dataFile) {
    warnIf(true, "FullEpisode", `Missing template data for "${template.dataFile}" in segment ${segment.id}`);
    // Render placeholder
    return (
      <AbsoluteFill
        style={{
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
        }}
      >
        <div
          style={{
            color: "#E5A544",
            fontFamily: "IBM Plex Mono, monospace",
            fontSize: 16,
          }}
        >
          ⚠️ {template.component}: {template.dataFile}
        </div>
      </AbsoluteFill>
    );
  }

  // Inject Whisper-resolved syncPoints from the manifest into the template's
  // _direction block. This is the bridge that makes useBeatSync actually fire.
  // The manifest stores syncPoints in absolute episode time; the template
  // (wrapped in <Sequence from={startFrame}>) sees frame 0 at segment start,
  // so we convert each timeSec to segment-relative by subtracting startSec.
  // Unresolved sync points (Whisper couldn't find the word) are filtered out.
  let dataWithSync = data;
  if (data && segment.syncPoints && segment.syncPoints.length > 0) {
    const relative = segment.syncPoints
      .filter((p): p is SyncPoint & { timeSec: number; frame: number } =>
        p.timeSec !== null && p.frame !== null,
      )
      .map((p) => ({
        word: p.word,
        timeSec: p.timeSec - segment.startSec,
        frame: p.frame - Math.round(segment.startSec * fps),
        confidence: p.confidence,
      }));
    if (relative.length > 0) {
      dataWithSync = {
        ...data,
        _direction: {
          ...(data._direction ?? {}),
          syncPoints: relative,
        },
      };
    }
  }

  return (
    <SegmentErrorBoundary
      segmentId={segment.id}
      componentName={template.component}
    >
      <AbsoluteFill>
        <Component data={dataWithSync} />
      </AbsoluteFill>
    </SegmentErrorBoundary>
  );
});

// ── Main composition ───���──────────────────────────────────────────────────────

export const FullEpisode: React.FC<FullEpisodeProps> = ({
  manifest,
  templateData,
  assetBasePath = "assets",
}) => {
  const { fps } = useVideoConfig();

  // Split segments into layers + build index for layered lookups.
  //
  // HOLD segments are merged into the preceding non-HOLD segment of the same
  // layer by extending that segment's endSec. The HOLD itself is dropped from
  // the rendering list. Effect: the previous visual sustains through the HOLD
  // window — for FOOTAGE the video keeps playing, for TEMPLATE the template
  // animation continues past its natural end (interpolate's clamp behavior
  // typically holds the final state). True last-frame freeze (per the
  // schema's `freeze: true` semantic) is approximated by extension; capturing
  // and re-rendering the literal last frame would require frame-state
  // snapshotting, deferred until the extension behavior proves insufficient.
  // Without this preprocessing HOLD segments fall through to BackgroundSegment
  // (which renders the asset-pending placeholder) or ForegroundSegment (which
  // renders nothing) — neither sustains the previous visual.
  const { backgroundSegs, foregroundSegs, segmentIndex } = useMemo(() => {
    const bg: ManifestSegment[] = [];
    const fg: ManifestSegment[] = [];
    const idx: Record<string, ManifestSegment> = {};

    // Pass 1: build per-layer ordered lists, indexing by id. HOLD segments
    // are routed to their layer like any other segment — pass 2 below
    // collapses them into the preceding non-HOLD on that layer.
    for (const seg of manifest.segments) {
      idx[seg.id] = seg;
      if (seg.layer === "foreground") {
        fg.push(seg);
      } else {
        bg.push(seg);
      }
    }

    // Pass 2: per layer, walk the ordered list and merge HOLDs into the
    // preceding non-HOLD by extending its endSec. Drop the HOLD itself.
    // Sort defensively in case the manifest isn't in time order.
    const mergeHolds = (segs: ManifestSegment[]): ManifestSegment[] => {
      const sorted = segs.slice().sort((a, b) => a.startSec - b.startSec);
      const out: ManifestSegment[] = [];
      for (const seg of sorted) {
        if (seg.type === "HOLD") {
          if (out.length === 0) {
            // HOLD with nothing before it on this layer — log and drop.
            // Without a preceding visual to sustain, it would render as a
            // placeholder; dropping it leaves a transparent gap, which is
            // strictly preferable.
            // eslint-disable-next-line no-console
            console.warn(
              `[FullEpisode] HOLD segment ${seg.id} has no preceding segment on layer "${seg.layer}" to sustain. Dropping.`,
            );
            continue;
          }
          // Extend the preceding segment's endSec to cover this HOLD window.
          // Replace the last entry with a copy carrying the extended end so
          // we don't mutate the input manifest.
          const prev = out[out.length - 1];
          out[out.length - 1] = { ...prev, endSec: Math.max(prev.endSec, seg.endSec) };
        } else {
          out.push(seg);
        }
      }
      return out;
    };

    const bgMerged = mergeHolds(bg);
    const fgMerged = mergeHolds(fg);

    // Identify background segments claimed by layered foregrounds —
    // these are rendered inside LayeredComposition, not standalone.
    // Note: this runs against the post-merge fg list; layered-bg references
    // by id still resolve via segmentIndex which holds the original (pre-
    // merge) segment objects.
    const claimedBgIds = new Set<string>();
    for (const seg of fgMerged) {
      if (seg.layered?.backgroundSegmentId) {
        claimedBgIds.add(seg.layered.backgroundSegmentId);
      }
    }

    const standaloneBg = bgMerged.filter((s) => !claimedBgIds.has(s.id));

    return {
      backgroundSegs: standaloneBg,
      foregroundSegs: fgMerged,
      segmentIndex: idx,
    };
  }, [manifest.segments]);

  // Extract audio cues from all segments for AudioLayer
  const segmentAudio = useMemo(() => {
    return manifest.segments
      .filter((seg) => seg.soundCue || seg.soundCueSecondary || (seg.textureCues && seg.textureCues.length > 0))
      .map((seg) => ({
        segmentId: seg.id,
        startSec: seg.startSec,
        soundCue: seg.soundCue,
        soundCueSecondary: seg.soundCueSecondary,
        textureCues: seg.textureCues,
      }));
  }, [manifest.segments]);

  const filmOverlayConfig = manifest.filmOverlay;
  const lowerThirdConfig = manifest.lowerThird;

  // Build visual layers (shared between overlay and non-overlay paths)
  const visualLayers = (
    <>
      {/* Layer 1: Background segments (footage, images) */}
      {backgroundSegs.map((seg) => {
        const startFrame = Math.round(seg.startSec * fps);
        const durationFrames = Math.round((seg.endSec - seg.startSec) * fps);

        if (durationFrames <= 0) return null;

        return (
          <Sequence
            key={seg.id}
            from={startFrame}
            durationInFrames={durationFrames}
            name={`bg-${seg.id}`}
          >
            <TransitionWrapper
              transitionIn={seg.transition?.in}
              transitionOut={seg.transition?.out}
              durationSec={seg.transition?.durationSec}
              durationInFrames={durationFrames}
            >
              <BackgroundSegment
                segment={seg}
                assetBasePath={assetBasePath}
              />
            </TransitionWrapper>
          </Sequence>
        );
      })}

      {/* Layer 2: Foreground segments (templates, transitions, layered) */}
      {foregroundSegs.map((seg) => {
        const startFrame = Math.round(seg.startSec * fps);
        const durationFrames = Math.round((seg.endSec - seg.startSec) * fps);

        if (durationFrames <= 0) return null;

        // Layered mode: foreground template composited over a background segment
        const layeredBgId = seg.layered?.backgroundSegmentId;
        const layeredBg = layeredBgId ? (segmentIndex[layeredBgId] ?? null) : null;
        warnIf(
          !!layeredBgId && !layeredBg,
          "FullEpisode",
          `Layered segment ${seg.id} references backgroundSegmentId "${layeredBgId}" which was not found in the manifest.`
        );

        return (
          <Sequence
            key={seg.id}
            from={startFrame}
            durationInFrames={durationFrames}
            name={layeredBg ? `layered-${seg.id}` : `fg-${seg.id}`}
          >
            <TransitionWrapper
              transitionIn={seg.transition?.in}
              transitionOut={seg.transition?.out}
              durationSec={seg.transition?.durationSec}
              durationInFrames={durationFrames}
            >
              {layeredBg ? (
                <LayeredComposition
                  position={seg.layered?.position}
                  blendMode={seg.layered?.blendMode}
                  foregroundOpacity={seg.layered?.foregroundOpacity}
                  backgroundDim={seg.layered?.backgroundDim}
                  foregroundFadeInSec={seg.layered?.foregroundFadeInSec}
                  vignette={seg.layered?.vignette}
                >
                  {{
                    background: (
                      <BackgroundSegment
                        segment={layeredBg}
                        assetBasePath={assetBasePath}
                      />
                    ),
                    foreground: (
                      <ForegroundSegment
                        segment={seg}
                        templateData={templateData}
                        fps={fps}
                      />
                    ),
                  }}
                </LayeredComposition>
              ) : (
                <ForegroundSegment
                  segment={seg}
                  templateData={templateData}
                  fps={fps}
                />
              )}
            </TransitionWrapper>
          </Sequence>
        );
      })}

      {/* Layer 3: Section indicator (persistent beat label) */}
      {manifest.beats && manifest.beats.length > 0 && (
        <SectionIndicator beats={manifest.beats} />
      )}

      {/* Layer 4: Lower-thirds (one per beat, driven by manifest) */}
      {lowerThirdConfig && manifest.beats && manifest.beats.map((beat) => {
        const enterDelay = lowerThirdConfig.enterDelaySec ?? 0.5;
        const displayDuration = lowerThirdConfig.displayDurationSec ?? 4;
        const enterFrame = Math.round((beat.startSec + enterDelay) * fps);
        const exitFrame = Math.round((beat.startSec + enterDelay + displayDuration) * fps);

        return (
          <Sequence
            key={`lt-${beat.id}`}
            from={0}
            durationInFrames={Math.round(manifest.totalDurationSec * fps)}
            name={`lower-third-${beat.id}`}
          >
            <LowerThird
              label={lowerThirdConfig.label}
              title={beat.title}
              mode={lowerThirdConfig.mode || "dark"}
              accentColor={lowerThirdConfig.accentColor}
              enterFrame={enterFrame}
              exitFrame={exitFrame}
            />
          </Sequence>
        );
      })}

      {/* Layer 4b: Light leaks at beat boundaries — subtle film-burn flash for cinematic transitions.
          One LightLeak per beat (skipping the first), 1.0s duration starting at beat boundary.
          Hue shifts gently per beat for variety; uses Remotion's built-in light-leaks effect. */}
      {manifest.beats && manifest.beats.slice(1).map((beat, idx) => {
        const burnDurationSec = 1.0;
        const startFrame = Math.round((beat.startSec - burnDurationSec * 0.3) * fps);
        const durationInFrames = Math.round(burnDurationSec * fps);
        // Rotate hue per beat: amber-warm → rose → cyan-cool → amber
        const hueShifts = [0, -25, 30, -10];
        const hueShift = hueShifts[idx % hueShifts.length];
        return (
          <Sequence
            key={`leak-${beat.id}`}
            from={Math.max(0, startFrame)}
            durationInFrames={durationInFrames}
            name={`light-leak-${beat.id}`}
          >
            <AbsoluteFill style={{ opacity: 0.4, mixBlendMode: "screen", pointerEvents: "none" }}>
              <LightLeak
                durationInFrames={durationInFrames}
                hueShift={hueShift}
                seed={beat.startSec * 1000}
              />
            </AbsoluteFill>
          </Sequence>
        );
      })}
    </>
  );

  return (
    <EpisodeColorEmphasisProvider value={manifest.episodeColorEmphasis}>
      {/*
       * EditorialSurface provides the paper background + grain layer that
       * unifies Remotion analytical content with the AI-generated illustration
       * pillar. Replaces the former hardcoded backgroundColor: "#F5F0E8".
       * Intensity 0.6 = "felt, not seen" — warmth before texture.
       */}
      <EditorialSurface intensity={0.6}>
        {filmOverlayConfig ? (
          <FilmOverlay
            effects={filmOverlayConfig.effects}
            intensity={filmOverlayConfig.intensity}
          >
            {visualLayers}
          </FilmOverlay>
        ) : (
          visualLayers
        )}

        {/* Audio layers (always outside film overlay — audio isn't visual) */}

        {/* Layer 5: Narration (dominant — -0dB reference) */}
        {manifest.narration.audioFile && (
          <Audio
            src={staticFile(
              `episodes/${manifest.episode.toLowerCase()}/${manifest.narration.audioFile}`
            )}
          />
        )}

        {/* Layers 6-8: Music bed + transition SFX + texture hits */}
        <AudioLayer
          episode={manifest.episode.toLowerCase()}
          musicBedTracks={manifest.musicBed?.tracks}
          segmentAudio={segmentAudio}
        />
      </EditorialSurface>
    </EpisodeColorEmphasisProvider>
  );
};

// ── Metadata calculator ───────────────────────────────────────────────────────

/**
 * calculateMetadata for Composition registration.
 * Reads totalDurationSec from the manifest and converts to frames.
 */
export function calculateFullEpisodeMetadata({
  props,
}: {
  props: FullEpisodeProps;
}) {
  const totalFrames = Math.ceil(props.manifest.totalDurationSec * props.manifest.fps);

  return {
    durationInFrames: totalFrames,
    fps: props.manifest.fps,
    width: layout.width,
    height: layout.height,
  };
}
