/**
 * FullEpisode — Assembly-manifest-driven episode composition.
 *
 * Replaces the manual EP01.tsx approach (27-clip Series) with a data-driven
 * composition that renders the COMPLETE video: narration audio, motion graphics,
 * stock footage with brand treatment, and transitions — all from one JSON file.
 *
 * Architecture:
 *   - Reads an assembly manifest (generated by tools/assembly/generate_manifest.py)
 *   - Bottom layer: background segments (FOOTAGE, IMAGE) with BrandImage treatment
 *   - Top layer: foreground segments (TEMPLATE, TRANSITION) positioned by timestamp
 *   - Audio layer: narration track via Remotion <Audio>
 *   - HOLD segments sustain the previous visual with an optional freeze
 *
 * Usage:
 *   Register as a Composition with the manifest as defaultProps or inputProps:
 *
 *   <Composition
 *     id="EP01-Full"
 *     component={FullEpisode}
 *     calculateMetadata={calculateFullEpisodeMetadata}
 *     defaultProps={{ manifestPath: "episodes/ep01/assembly-manifest.json" }}
 *   />
 *
 * Then render:
 *   npx remotion render EP01-Full out/ep01-full.mp4
 *
 * Render performance notes (from research):
 *   - Uses <OffthreadVideo> instead of <Video> for stock footage segments.
 *     Extracts frames off-thread, preventing cache eviction stalls that hit
 *     at 20-30% progress in long compositions with many short clips.
 *   - BackgroundSegment and ForegroundSegment are memoized to prevent
 *     SVG filter re-creation per frame (Chrome throttles overlapping video+SVG).
 *   - For Lambda: use memorySizeInMb: 3008 and concurrency: 4.
 *     18 min @ 1080p30 renders in ~2-5 min, well within the 5 GB file limit.
 */

import React, { useMemo, memo } from "react";
import {
  AbsoluteFill,
  Audio,
  Img,
  OffthreadVideo,
  Sequence,
  staticFile,
  useCurrentFrame,
  useVideoConfig,
  interpolate,
} from "remotion";
import { layout, sec, durations } from "../../design/theme";
import { CLAMP } from "../../utils/animation";
import { BrandImage } from "../../components/BrandImage";
import { SectionIndicator } from "../../components/SectionIndicator";

// ── Template imports ─��────────────────────────────────────────────────────────

import { TitleTransition } from "../TitleTransition/TitleTransition";
import { ChoroplethMap } from "../ChoroplethMap/ChoroplethMap";
import { KineticTypography } from "../KineticTypography/KineticTypography";
import { TimelineComparison } from "../TimelineComparison/TimelineComparison";
import { DataChart } from "../DataChart/DataChart";
import { FrameworkDiagram } from "../FrameworkDiagram/FrameworkDiagram";
import { RouteAnimation } from "../RouteAnimation/RouteAnimation";

// ── Types ──────���─────────────────────────────��────────────────────────────────

type SegmentType = "FOOTAGE" | "IMAGE" | "TEMPLATE" | "TRANSITION" | "HOLD";
type LayerType = "background" | "foreground";
type DuotoneRamp = "standard" | "conflict" | "editorial";
type CompositeMode = "background" | "inset" | "antipode" | "raw";
type TransitionType = "cut" | "dissolve" | "fade";

interface AssetInfo {
  shotListId?: string;
  searchTerms?: string[];
  source?: string;
  file?: string;
  status?: "pending" | "resolved" | "failed";
  placeholder?: "solid-color" | "last-frame";
  fallbackColor?: string;
}

interface TreatmentInfo {
  ramp?: DuotoneRamp;
  composite?: CompositeMode;
  opacity?: number;
}

interface TemplateInfo {
  component: string;
  dataFile?: string;
}

interface HoldInfo {
  freeze?: boolean;
}

interface TransitionInfo {
  in?: TransitionType;
  out?: TransitionType;
  durationSec?: number;
}

interface ManifestSegment {
  id: string;
  type: SegmentType;
  startSec: number;
  endSec: number;
  layer: LayerType;
  beat?: string;
  priority?: string;
  narrationRef?: string;
  asset?: AssetInfo;
  treatment?: TreatmentInfo;
  template?: TemplateInfo;
  hold?: HoldInfo;
  transition?: TransitionInfo;
  notes?: string;
}

interface NarrationInfo {
  audioFile?: string;
  totalDurationSec: number;
  words?: Array<{ word: string; start: number; end: number }>;
}

interface BeatInfo {
  id: string;
  title: string;
  startSec: number;
  endSec?: number;
}

interface AssemblyManifest {
  version: string;
  episode: string;
  title?: string;
  fps: number;
  totalDurationSec: number;
  mode: "estimate" | "precise";
  narration: NarrationInfo;
  beats?: BeatInfo[];
  segments: ManifestSegment[];
}

// ── Props ────────────────────────────���────────────────────────────────────────

interface FullEpisodeProps {
  /** The assembly manifest data (passed as inputProps or loaded inline). */
  manifest: AssemblyManifest;
  /**
   * Map of data file names → loaded JSON data for Remotion templates.
   * Keys are the dataFile values from manifest segments (e.g. "kinetic-92-yield.json").
   * This must be passed in because Remotion can't do dynamic imports at render time.
   */
  templateData: Record<string, any>;
  /**
   * Base path for resolved asset files (footage/images).
   * Assets are resolved as: staticFile(`${assetBasePath}/${segment.asset.file}`)
   */
  assetBasePath?: string;
}

// ── Component map ─────────────────────────────────────────────────────────────

// Composite mode opacity defaults (mirrors BrandImage.tsx COMPOSITE_OPACITY)
const COMPOSITE_DEFAULTS: Record<string, number> = {
  background: 0.35,
  inset: 0.7,
  antipode: 0.45,
  raw: 1.0,
};

const TEMPLATE_COMPONENTS: Record<string, React.ComponentType<{ data: any }>> = {
  TitleTransition,
  ChoroplethMap,
  KineticTypography,
  TimelineComparison,
  DataChart,
  FrameworkDiagram,
  RouteAnimation,
};

// ── Fade wrapper ──────────────────────────────────────────────────────────────

const FadeWrapper: React.FC<{
  children: React.ReactNode;
  transitionIn?: TransitionType;
  transitionOut?: TransitionType;
  transitionDurationSec?: number;
  durationInFrames: number;
}> = ({
  children,
  transitionIn = "cut",
  transitionOut = "cut",
  transitionDurationSec = 0.5,
  durationInFrames,
}) => {
  const frame = useCurrentFrame();
  const fadeDur = sec(transitionDurationSec);

  let opacity = 1;
  let scale = 1;

  // Fade/dissolve in
  if (transitionIn === "fade" || transitionIn === "dissolve") {
    const inProgress = interpolate(frame, [0, fadeDur], [0, 1], CLAMP);
    opacity = Math.min(opacity, inProgress);
    // Dissolve gets a subtle zoom-in (1.02 → 1.0) for depth
    if (transitionIn === "dissolve") {
      scale = interpolate(inProgress, [0, 1], [1.02, 1], CLAMP);
    }
  }

  // Fade/dissolve out
  if (transitionOut === "fade" || transitionOut === "dissolve") {
    const outProgress = interpolate(
      frame,
      [durationInFrames - fadeDur, durationInFrames],
      [1, 0],
      CLAMP
    );
    opacity = Math.min(opacity, outProgress);
    // Dissolve out: subtle zoom-out (1.0 → 0.98) — receding
    if (transitionOut === "dissolve") {
      scale = Math.min(
        scale,
        interpolate(outProgress, [1, 0], [1, 0.98], CLAMP)
      );
    }
  }

  const needsTransform = scale !== 1;

  return (
    <AbsoluteFill
      style={{
        opacity,
        ...(needsTransform && {
          transform: `scale(${scale})`,
          transformOrigin: "center center",
        }),
      }}
    >
      {children}
    </AbsoluteFill>
  );
};

// ── Background segment renderer ──────────────────────────────────────────────
// Memoized to prevent SVG filter re-creation on every frame. Each segment
// gets its own BrandImage filter instance, avoiding Chrome throttling when
// multiple video+SVG-filter combos overlap during transitions.

const BackgroundSegment: React.FC<{
  segment: ManifestSegment;
  assetBasePath: string;
}> = memo(({ segment, assetBasePath }) => {
  const { asset, treatment } = segment;

  // Determine placeholder style based on asset status
  const assetStatus = asset?.status || (asset?.file ? "resolved" : "pending");

  if (assetStatus !== "resolved" || !asset?.file) {
    // Asset not yet sourced — render branded placeholder
    const placeholderType = asset?.placeholder || "solid-color";
    const bgColor = placeholderType === "solid-color"
      ? (asset?.fallbackColor || "#F5F0E8")
      : "#F5F0E8";

    return (
      <AbsoluteFill
        style={{
          backgroundColor: bgColor,
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
        }}
      >
        <div
          style={{
            color: "#6A6458",
            fontFamily: "IBM Plex Mono, monospace",
            fontSize: 16,
            textAlign: "center",
            padding: 40,
            maxWidth: 600,
          }}
        >
          <div style={{ fontSize: 28, marginBottom: 8 }}>
            {segment.type === "FOOTAGE" ? "▶" : "▣"}
          </div>
          <div>{asset?.shotListId || asset?.searchTerms?.[0] || segment.id}</div>
          {assetStatus === "failed" && (
            <div style={{ color: "#C23B22", marginTop: 4 }}>ASSET FAILED</div>
          )}
        </div>
      </AbsoluteFill>
    );
  }

  const src = staticFile(`${assetBasePath}/${asset.file}`);
  const ramp = treatment?.ramp || "standard";
  const composite = treatment?.composite || "background";
  const opacity = treatment?.opacity;

  if (segment.type === "FOOTAGE") {
    // Video asset: OffthreadVideo for stable sequential rendering.
    // OffthreadVideo extracts frames outside the main thread, avoiding
    // cache eviction stalls that <Video> hits at 20-30% render progress
    // in long compositions with many short clips.
    return (
      <AbsoluteFill style={{ opacity: opacity ?? COMPOSITE_DEFAULTS[composite] }}>
        <BrandImage
          src="" // BrandImage filter applied to the container; video below
          ramp={ramp as any}
          composite="raw"
          opacity={1}
        >
          <OffthreadVideo
            src={src}
            style={{
              width: "100%",
              height: "100%",
              objectFit: "cover",
            }}
          />
        </BrandImage>
      </AbsoluteFill>
    );
  }

  // IMAGE — still photo/archival with brand treatment
  return (
    <BrandImage
      src={src}
      ramp={ramp as any}
      composite={composite as any}
      opacity={opacity}
    />
  );
});

// ── Foreground segment renderer ──��───────────────────────────────────────────

const ForegroundSegment: React.FC<{
  segment: ManifestSegment;
  templateData: Record<string, any>;
}> = memo(({ segment, templateData }) => {
  const { template } = segment;

  if (!template?.component) {
    return null;
  }

  const Component = TEMPLATE_COMPONENTS[template.component];
  if (!Component) {
    console.warn(
      `FullEpisode: Unknown template component "${template.component}" in segment ${segment.id}`
    );
    return null;
  }

  const data = template.dataFile ? templateData[template.dataFile] : null;
  if (!data && template.dataFile) {
    console.warn(
      `FullEpisode: Missing template data for "${template.dataFile}" in segment ${segment.id}`
    );
    // Render placeholder
    return (
      <AbsoluteFill
        style={{
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
        }}
      >
        <div
          style={{
            color: "#E5A544",
            fontFamily: "IBM Plex Mono, monospace",
            fontSize: 16,
          }}
        >
          ⚠️ {template.component}: {template.dataFile}
        </div>
      </AbsoluteFill>
    );
  }

  return (
    <AbsoluteFill>
      <Component data={data} />
    </AbsoluteFill>
  );
});

// ── Main composition ───���──────────────────────────────────────────────────────

export const FullEpisode: React.FC<FullEpisodeProps> = ({
  manifest,
  templateData,
  assetBasePath = "assets",
}) => {
  const { fps } = useVideoConfig();

  // Split segments into layers
  const { backgroundSegs, foregroundSegs } = useMemo(() => {
    const bg: ManifestSegment[] = [];
    const fg: ManifestSegment[] = [];

    for (const seg of manifest.segments) {
      if (seg.layer === "foreground") {
        fg.push(seg);
      } else {
        bg.push(seg);
      }
    }

    return { backgroundSegs: bg, foregroundSegs: fg };
  }, [manifest.segments]);

  return (
    <AbsoluteFill style={{ backgroundColor: "#F5F0E8" }}>
      {/* Layer 0: Dark background base */}

      {/* Layer 1: Background segments (footage, images) */}
      {backgroundSegs.map((seg) => {
        const startFrame = Math.round(seg.startSec * fps);
        const durationFrames = Math.round((seg.endSec - seg.startSec) * fps);

        if (durationFrames <= 0) return null;

        return (
          <Sequence
            key={seg.id}
            from={startFrame}
            durationInFrames={durationFrames}
            name={`bg-${seg.id}`}
          >
            <FadeWrapper
              transitionIn={seg.transition?.in}
              transitionOut={seg.transition?.out}
              transitionDurationSec={seg.transition?.durationSec}
              durationInFrames={durationFrames}
            >
              <BackgroundSegment
                segment={seg}
                assetBasePath={assetBasePath}
              />
            </FadeWrapper>
          </Sequence>
        );
      })}

      {/* Layer 2: Foreground segments (templates, transitions) */}
      {foregroundSegs.map((seg) => {
        const startFrame = Math.round(seg.startSec * fps);
        const durationFrames = Math.round((seg.endSec - seg.startSec) * fps);

        if (durationFrames <= 0) return null;

        return (
          <Sequence
            key={seg.id}
            from={startFrame}
            durationInFrames={durationFrames}
            name={`fg-${seg.id}`}
          >
            <FadeWrapper
              transitionIn={seg.transition?.in}
              transitionOut={seg.transition?.out}
              transitionDurationSec={seg.transition?.durationSec}
              durationInFrames={durationFrames}
            >
              <ForegroundSegment
                segment={seg}
                templateData={templateData}
              />
            </FadeWrapper>
          </Sequence>
        );
      })}

      {/* Layer 3: Section indicator (persistent beat label) */}
      {manifest.beats && manifest.beats.length > 0 && (
        <SectionIndicator beats={manifest.beats} />
      )}

      {/* Layer 4: Narration audio */}
      {manifest.narration.audioFile && (
        <Audio
          src={staticFile(
            `episodes/${manifest.episode.toLowerCase()}/${manifest.narration.audioFile}`
          )}
        />
      )}
    </AbsoluteFill>
  );
};

// ── Metadata calculator ───────────────────────────────────────────────────────

/**
 * calculateMetadata for Composition registration.
 * Reads totalDurationSec from the manifest and converts to frames.
 */
export function calculateFullEpisodeMetadata({
  props,
}: {
  props: FullEpisodeProps;
}) {
  const totalFrames = Math.ceil(props.manifest.totalDurationSec * props.manifest.fps);

  return {
    durationInFrames: totalFrames,
    fps: props.manifest.fps,
    width: layout.width,
    height: layout.height,
  };
}
