#!/usr/bin/env python3
"""
blind_review.py — A/B compare two scripts BLINDLY, eliminating recency
bias from the reviewer (human or LLM agent).

Authors instinctively favor their newest version. The audit skill, if
given two scripts in order, may show similar bias toward whichever it
sees second (recency) or first (anchoring). This tool removes the
bias mechanically:

  1. Both scripts are rendered to readable docs via format_for_reading.
  2. Production metadata (version headers, claim-tag annotations,
     `**Script version:** v5.6` / `v6.2` text) is stripped from the
     readable doc so the reviewer can't tell which is older.
  3. The two anonymized read-docs are randomly assigned labels
     "Script A" and "Script B." Coin flip — half the time A=v5 and
     half the time A=v6.
  4. The randomized pair is passed to a reviewing agent with a
     structured prompt: which is the stronger cold open, where would
     viewers drop, which would you watch all the way through, etc.
     The agent never sees the version labels.
  5. The reviewer's verdict is captured.
  6. AFTER capture, the version-label mapping is revealed in the
     output. The reviewer's reasoning stands; we now know which
     script the reviewer actually preferred without bias.

This is the most powerful debiasing instrument in the narration
pipeline. Pair with `script_diff.py` for full A/B coverage:
script_diff gives you structural metrics; blind_review gives you
qualitative reader response.

Usage:
    python3 tools/narration/blind_review.py <script_a> <script_b>
    python3 tools/narration/blind_review.py <a> <b> --seed 42
    python3 tools/narration/blind_review.py <a> <b> -o review.md

The --seed flag pins the random label assignment for reproducibility
(useful for tests or repeated reviewer rounds).
"""

from __future__ import annotations

import argparse
import random
import re
import sys
from dataclasses import dataclass
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "shared"))
from paths import get_project_root  # noqa: E402

sys.path.insert(0, str(Path(__file__).resolve().parent))
import format_for_reading as ffr  # noqa: E402

ROOT = get_project_root()


# ── Sanitization ────────────────────────────────────────────────────────────
# Strip any production metadata that would reveal version identity to the
# reviewer. Operates on a string (the rendered read-doc), returns the
# sanitized version.

# Markers / lines that uniquely identify a version. Order matters — apply
# the most specific patterns first to avoid partial matches breaking
# more general ones later.
_VERSION_PATTERNS = [
    # Header line: "# Narration — prisoners-dilemma" → "# Narration — Script"
    re.compile(r"^# Narration — [^\n]+", re.MULTILINE),
    # Version-specific footers / re-run instructions
    re.compile(r"_Regenerate: `python3[^`]+`_", re.MULTILINE),
    # Generic "auto-generated by ... script-v6-production.md" tells
    re.compile(r"script-v\d+(?:\.\d+)?(?:-production)?\.md"),
    # Bare version mentions in the doc body
    re.compile(r"\bv\d+(?:\.\d+){1,2}\b", re.IGNORECASE),
]


def sanitize_read_doc(text: str, label: str) -> str:
    """Strip every version-identifying marker; replace title with neutral label.

    `label` is the reviewer-facing tag ("Script A" or "Script B"). After
    sanitization the reviewer sees a generic narration document with no
    references to v5, v6, the slug, or the source filename.
    """
    out = text
    out = _VERSION_PATTERNS[0].sub(f"# Narration — {label}", out)
    # Drop the regenerate footer entirely
    out = _VERSION_PATTERNS[1].sub("", out)
    # Strip script filename mentions
    out = _VERSION_PATTERNS[2].sub("[script file]", out)
    # Strip bare version mentions
    out = _VERSION_PATTERNS[3].sub("[version]", out)
    return out


# ── Label assignment ────────────────────────────────────────────────────────


@dataclass
class LabelAssignment:
    """Bookkeeping for blind labels: which actual file is hidden behind
    which reviewer-facing label."""

    script_a_path: Path        # filesystem path labeled "Script A" to reviewer
    script_b_path: Path        # filesystem path labeled "Script B" to reviewer
    a_is_first_input: bool     # True if Script A is the FIRST CLI arg; False if A=second input

    @property
    def reveal_summary(self) -> str:
        return (
            f"**Reveal:** Script A = `{self.script_a_path.name}`, "
            f"Script B = `{self.script_b_path.name}`"
        )


def randomly_assign_labels(
    path_first: Path, path_second: Path, seed: int | None = None,
) -> LabelAssignment:
    """Coin flip — half the time A=first_arg, half the time A=second_arg.

    The reviewer doesn't get to see which CLI arg corresponds to which
    label. seed=None uses real entropy; pin for reproducibility (tests
    or controlled-comparison rounds).
    """
    rng = random.Random(seed)
    a_is_first = rng.random() < 0.5
    if a_is_first:
        return LabelAssignment(
            script_a_path=path_first, script_b_path=path_second, a_is_first_input=True,
        )
    return LabelAssignment(
        script_a_path=path_second, script_b_path=path_first, a_is_first_input=False,
    )


# ── Read-doc rendering with sanitization ─────────────────────────────────────


def render_sanitized_read_doc(script_path: Path, label: str) -> str:
    """Parse a script and render as a sanitized read-doc for the reviewer."""
    beats = ffr.parse_script(script_path)
    raw = ffr.render_read_doc(beats, slug=label, wpm=ffr.DEFAULT_WPM, breath_marks=False)
    return sanitize_read_doc(raw, label=label)


# ── Reviewer prompt construction ────────────────────────────────────────────


REVIEWER_PROMPT_TEMPLATE = """You are doing a blind A/B comparison of two production scripts for a YouTube
video essay channel (geopolitics + historical-analogy register; intellectually
serious; "smart friend over drinks" tone; bounded-analogy editorial doctrine).

You will see TWO scripts labeled "Script A" and "Script B." You do NOT know
which is newer, which is the author's preferred version, or which is the
canonical. The labels are randomized.

**Your job:** answer five structured questions about how the two compare.
Don't try to guess which is the newer version — that's not the point.

The two scripts:

=========================================
SCRIPT A
=========================================

{script_a_text}

=========================================
SCRIPT B
=========================================

{script_b_text}

=========================================

Answer these five questions, in order. Be concrete — cite specific lines or
beats. Don't pad. Aim for a paragraph per question.

1. **Cold-open verdict.** Which script's cold open is stronger and why? When
   does the hook land in each? (Hook = the moment a viewer commits to keep
   watching.) If you had to bet on retention through the first 90 seconds,
   which one wins?

2. **Mid-section retention prediction.** For each script, identify where you
   predict viewers would drop off. Don't assume both versions have the same
   risk — call out specific paragraphs / beats where attention is most
   vulnerable. Which mid-section feels less likely to lose viewers?

3. **Named-concept reveal.** Each script names a concept ("The Wrong Game").
   Does that name land harder in one version than the other? Why? Is it
   earned (felt like a payoff) or declared (felt like a label)?

4. **Bounded-analogy doctrine.** Both scripts use the "this is useful here,
   misleading there" caveat pattern. Which version delivers caveats with
   sharper conviction (one-clause asides) vs. which version hedges in
   longer paragraphs that drain confidence? Specific examples.

5. **Overall: which would you watch end to end, and why?** This is your
   final verdict. Pick A or B. Give one-paragraph reasoning. The reasoning
   matters more than the pick.

After your five answers, give a final one-sentence summary of your verdict.
"""


def build_reviewer_prompt(script_a_text: str, script_b_text: str) -> str:
    return REVIEWER_PROMPT_TEMPLATE.format(
        script_a_text=script_a_text, script_b_text=script_b_text,
    )


# ── Top-level orchestrator ──────────────────────────────────────────────────


def prepare_blind_pair(
    script_a: Path, script_b: Path, seed: int | None = None,
) -> tuple[LabelAssignment, str]:
    """Randomize labels + build the prompt. Returns (assignment, prompt_text)
    so the caller can hand the prompt to whichever reviewer they choose
    (LLM agent, human via terminal, etc.) and capture the verdict."""
    assignment = randomly_assign_labels(script_a, script_b, seed=seed)
    a_text = render_sanitized_read_doc(assignment.script_a_path, label="Script A")
    b_text = render_sanitized_read_doc(assignment.script_b_path, label="Script B")
    prompt = build_reviewer_prompt(a_text, b_text)
    return assignment, prompt


# ── Rendering ────────────────────────────────────────────────────────────────


def render_review_report(
    assignment: LabelAssignment, reviewer_verdict: str,
    name_first: str, name_second: str, prompt_excerpt: str = "",
) -> str:
    """Render the final blind-review report: prompt summary + verdict +
    reveal section that maps reviewer labels back to source files."""
    lines: list[str] = [
        "# Blind Review Report",
        "",
        "## Setup",
        "",
        "- **Reviewer:** [LLM agent / human — fill in]",
        f"- **Input A (first CLI arg):** `{name_first}`",
        f"- **Input B (second CLI arg):** `{name_second}`",
        "- **Random seed:** [seed value used]",
        "",
        "## Reviewer verdict (blind — labels A/B do NOT correspond to input order)",
        "",
        reviewer_verdict,
        "",
        "---",
        "",
        "## Label reveal",
        "",
        assignment.reveal_summary,
        "",
        (
            f"_The reviewer's 'Script A' was actually the **{'first' if assignment.a_is_first_input else 'second'}** "
            f"CLI argument (`{assignment.script_a_path.name}`)._"
        ),
        "",
        "## How to read this",
        "",
        "The reviewer answered all questions WITHOUT knowing which label",
        "corresponded to which source file. Their verdict on \"Script A\" vs",
        "\"Script B\" is therefore unbiased by recency, authorship, or",
        "filename. The reveal above translates back: if the reviewer picked",
        "Script B as the stronger version, you now know which actual script",
        "that was.",
        "",
        "For full A/B coverage, pair with `script_diff.py` for the structural",
        "metrics view.",
    ]
    return "\n".join(lines) + "\n"


# ── CLI ──────────────────────────────────────────────────────────────────────


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[1])
    parser.add_argument("script_a", help="First script path (CLI order, not reviewer label).")
    parser.add_argument("script_b", help="Second script path.")
    parser.add_argument(
        "--seed", type=int,
        help="Pin the random label assignment for reproducibility.",
    )
    parser.add_argument(
        "--prompt-only", action="store_true",
        help="Print the reviewer prompt + label mapping; don't invoke any reviewer. "
             "Useful for piping into a human reviewer or external LLM.",
    )
    parser.add_argument("-o", "--output", help="Write to file instead of stdout.")
    args = parser.parse_args()

    path_a = Path(args.script_a).resolve()
    path_b = Path(args.script_b).resolve()
    for p in (path_a, path_b):
        if not p.is_file():
            print(f"✗ script not found: {p}", file=sys.stderr)
            return 2

    assignment, prompt = prepare_blind_pair(path_a, path_b, seed=args.seed)

    if args.prompt_only:
        # Emit the prompt + the reveal mapping in stderr (so it doesn't
        # get piped into the reviewer accidentally — reveal stays separate).
        sys.stdout.write(prompt)
        sys.stderr.write(
            f"\n\n[label reveal — for after the review is captured]\n"
            f"  Script A = {assignment.script_a_path.name}\n"
            f"  Script B = {assignment.script_b_path.name}\n"
            f"  (a_is_first_input: {assignment.a_is_first_input})\n"
        )
        return 0

    # Default mode: print the prompt + the reveal mapping as a single
    # report scaffold the operator can fill in with a reviewer's actual
    # verdict. Full automation (spawn an Agent automatically) is
    # deliberately not the default — review quality varies enough that
    # the human-in-the-loop step matters.
    report = render_review_report(
        assignment=assignment,
        reviewer_verdict="_[Paste reviewer's structured verdict here — see prompt below]_",
        name_first=path_a.name, name_second=path_b.name,
    )
    output = (
        report
        + "\n---\n\n## Reviewer prompt (paste this into your reviewer of choice)\n\n```\n"
        + prompt
        + "\n```\n"
    )

    if args.output:
        out_path = Path(args.output).resolve()
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(output, encoding="utf-8")
        rel = out_path.relative_to(ROOT) if out_path.is_relative_to(ROOT) else out_path
        print(f"✓ wrote {rel}")
        print(f"  Reveal: Script A → {assignment.script_a_path.name}, "
              f"Script B → {assignment.script_b_path.name}")
        return 0
    sys.stdout.write(output)
    return 0


if __name__ == "__main__":
    sys.exit(main())
